/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import com.formdev.flatlaf.FlatLightLaf;
import com.mysql.jdbc.exceptions.jdbc4.CommunicationsException;
import extend.UserListCellRenderer;
import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author etien
 */
public class ConfigMachine extends javax.swing.JFrame {
    
    private static Connection conn = Bdd.coBdd();
    
    private static boolean statutModifUSER = false;
    private static boolean statutCréaUSER = false;
    private static boolean ERRCréaUSER = false;
    
    private static int idClientComptoir;
    
    private static String idConf_Ets;
    private static String C_EtsEnseigne;
    private static String C_EtsTélephone;
    private static String C_EtsEmail;
    private static String C_EtsNomRue;
    private static String C_EtsVille;
    private static String C_EtsCodePostal;
    private static String C_EtsFormeJuridique;
    private static String C_EtsCapitale;
    private static String C_EtsNoTVA;
    private static String C_EtsNoSIREN;
    private static String C_EtsNoSIRET;
    private static String C_EtsCodeNAF;
    private static String C_EtsNoRCF;

    
    private static int idChoisi;
    private static String[][] identifiant = new String[20][2]; 
    private static int typeChoisi;
    private static String[][] typeID = new String[20][2];
    
    
    private static Object[][] palierR = new Object[countPalierR()][3];
    private static String [] nomColPalierR = { "Numero Palier", "Palier en Point", "Reduction en Euro"};
    
    /**
     * Creates new form ConfigMachine
     */
    public ConfigMachine() {
        initComponents();
        URL iconURL = getClass().getResource(Données.getUrl_Logo());
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        jDialogConfValidIDComptoir.setLocationRelativeTo(this);
        
        recupIdUser();
        recupTypeID();
        recupIDclientC();
        recupEuroPts();
        
        //initalisation variables config magasin
        jTextFieldEnseigne.setText(C_EtsEnseigne);
        jTextFieldTélephone.setText(C_EtsTélephone);
        jTextFieldEmail.setText(C_EtsEmail);
        jTextFieldNomRue.setText(C_EtsNomRue);
        jTextFieldVille.setText(C_EtsVille);
        jTextFieldCodePostale.setText(C_EtsCodePostal);
        jTextFieldFormeJuridique.setText(C_EtsFormeJuridique);
        jTextFieldCapitale.setText(C_EtsCapitale);
        jTextFieldNoTVA.setText(C_EtsNoTVA);
        jTextFieldNoSIREN.setText(C_EtsNoSIREN);
        jTextFieldNoSIRET.setText(C_EtsNoSIRET);
        jTextFieldCodeNAF.setText(C_EtsCodeNAF);
        jTextFieldNoRCF.setText(C_EtsNoRCF);
        jTextFieldIdClientComptoir.setText(String.valueOf(idClientComptoir));
        
       int i =0;
       while (typeID[i][0] != null &&i < typeID.length){
            ListeTypes.addItem(typeID[i][0]);
            i++;
        } 
        i =0;
        while (identifiant[i][0] != null &&i < identifiant.length){
            ListeIdentifant.addItem(identifiant[i][0]);
            i++;
        }
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialogConfValidIDComptoir = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jButtonCSNon = new javax.swing.JButton();
        jButtonCSOui = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        NomLogiciel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ConfigLogic = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldIdClientComptoir = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        bValidIDclientC = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldRaportPTS = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonValiderDonnéesMag1 = new javax.swing.JButton();
        jButtonValiderDonnéesMag2 = new javax.swing.JButton();
        DonnéesMag = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEnseigne = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTélephone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNoTVA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNoSIREN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNoSIRET = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNomRue = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldVille = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCodePostale = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldCapitale = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldFormeJuridique = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCodeNAF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNoRCF = new javax.swing.JTextField();
        jButtonValiderDonnéesMag = new javax.swing.JButton();
        CompteUSER = new javax.swing.JPanel();
        ListeIdentifant = new javax.swing.JComboBox<>();
        jButtonAjoutUSER = new javax.swing.JButton();
        jButtonModifUSER = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldIdentifiant = new javax.swing.JTextField();
        jPasswordFieldMDP = new javax.swing.JPasswordField();
        ListeTypes = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jRadioButtonActif = new javax.swing.JRadioButton();
        jRadioButtonInactif = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jDialogConfValidIDComptoir.setAlwaysOnTop(true);
        jDialogConfValidIDComptoir.setSize(new java.awt.Dimension(400, 214));

        jPanel4.setMinimumSize(new java.awt.Dimension(400, 176));

        jButtonCSNon.setText("NON");
        jButtonCSNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSNonActionPerformed(evt);
            }
        });

        jButtonCSOui.setBackground(new java.awt.Color(255, 102, 102));
        jButtonCSOui.setText("OUI");
        jButtonCSOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSOuiActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Etes vous sûr de modifier l'ID du client comptoir ?");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Cette action peut entrainer un problème de creation");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("de tickets de caisse ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonCSOui, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonCSNon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCSNon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCSOui, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jDialogConfValidIDComptoirLayout = new javax.swing.GroupLayout(jDialogConfValidIDComptoir.getContentPane());
        jDialogConfValidIDComptoir.getContentPane().setLayout(jDialogConfValidIDComptoirLayout);
        jDialogConfValidIDComptoirLayout.setHorizontalGroup(
            jDialogConfValidIDComptoirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogConfValidIDComptoirLayout.setVerticalGroup(
            jDialogConfValidIDComptoirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Données.getNomLogiciel() + " | Configuration Général ");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NomLogiciel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomLogiciel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel24.setText("Paramétrage du client comptoir :");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("ID Client compoir :");

        jTextFieldIdClientComptoir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 51, 51));
        jLabel23.setText("Attention : l'ID client comptoir doit être correct");

        bValidIDclientC.setBackground(new java.awt.Color(51, 255, 0));
        bValidIDclientC.setText("Valider *");
        bValidIDclientC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValidIDclientCActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel25.setText("Par default 1");

        javax.swing.GroupLayout ConfigLogicLayout = new javax.swing.GroupLayout(ConfigLogic);
        ConfigLogic.setLayout(ConfigLogicLayout);
        ConfigLogicLayout.setHorizontalGroup(
            ConfigLogicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfigLogicLayout.createSequentialGroup()
                .addGroup(ConfigLogicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ConfigLogicLayout.createSequentialGroup()
                        .addGroup(ConfigLogicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ConfigLogicLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel24))
                            .addGroup(ConfigLogicLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel22)
                                .addGap(44, 44, 44)
                                .addComponent(jTextFieldIdClientComptoir)))
                        .addGap(53, 53, 53)
                        .addComponent(bValidIDclientC, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ConfigLogicLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfigLogicLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ConfigLogicLayout.setVerticalGroup(
            ConfigLogicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfigLogicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(ConfigLogicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ConfigLogicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(jTextFieldIdClientComptoir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bValidIDclientC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(ConfigLogicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(502, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Configuration Logiciel", ConfigLogic);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Configuration des cartes de fidelitées :");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Valeure des points : ");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("points");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("1 € TTC vaut :");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Palier des réductions :");

        UserListCellRenderer cellRenderer = new UserListCellRenderer();
        jTable1.setDefaultRenderer(Integer.class, cellRenderer);
        jTable1.setDefaultRenderer(Float.class, cellRenderer);
        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            palierR,
            nomColPalierR) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };

            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(51, 153, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(130, 244, 15));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jButtonValiderDonnéesMag1.setBackground(new java.awt.Color(51, 255, 51));
        jButtonValiderDonnéesMag1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonValiderDonnéesMag1.setText("Valider");
        jButtonValiderDonnéesMag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderDonnéesMag1ActionPerformed(evt);
            }
        });

        jButtonValiderDonnéesMag2.setBackground(new java.awt.Color(51, 255, 51));
        jButtonValiderDonnéesMag2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonValiderDonnéesMag2.setText("Valider");
        jButtonValiderDonnéesMag2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderDonnéesMag2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(163, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButtonValiderDonnéesMag2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel30))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(jTextFieldRaportPTS, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32)
                                .addGap(42, 42, 42)
                                .addComponent(jButtonValiderDonnéesMag1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel34))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(156, 156, 156)
                    .addComponent(jLabel33)
                    .addContainerGap(831, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel30)
                .addGap(43, 43, 43)
                .addComponent(jLabel31)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRaportPTS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonValiderDonnéesMag1))
                .addGap(64, 64, 64)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonValiderDonnéesMag2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(472, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Géstion fidélité", jPanel2);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Enseigne :");

        jTextFieldEnseigne.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Télephone :");

        jTextFieldTélephone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Email :");

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("N° TVA Intracommunautaire :  ");

        jTextFieldNoTVA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("N° SIREN :");

        jTextFieldNoSIREN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("N° SIRET :");

        jTextFieldNoSIRET.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Nom de la Rue :");

        jTextFieldNomRue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Ville :");

        jTextFieldVille.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Code Postal :");

        jTextFieldCodePostale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Montant Capital :");

        jTextFieldCapitale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Forme Juridique");

        jTextFieldFormeJuridique.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Code NAF :");

        jTextFieldCodeNAF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("N° RCF :");

        jTextFieldNoRCF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButtonValiderDonnéesMag.setBackground(new java.awt.Color(51, 255, 51));
        jButtonValiderDonnéesMag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonValiderDonnéesMag.setText("Valider");
        jButtonValiderDonnéesMag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderDonnéesMagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DonnéesMagLayout = new javax.swing.GroupLayout(DonnéesMag);
        DonnéesMag.setLayout(DonnéesMagLayout);
        DonnéesMagLayout.setHorizontalGroup(
            DonnéesMagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DonnéesMagLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(DonnéesMagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DonnéesMagLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldNoSIRET, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DonnéesMagLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldNoSIREN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DonnéesMagLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldNoTVA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DonnéesMagLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldEnseigne, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DonnéesMagLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldTélephone, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DonnéesMagLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DonnéesMagLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldCodeNAF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DonnéesMagLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldNoRCF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(DonnéesMagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DonnéesMagLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldNomRue, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DonnéesMagLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DonnéesMagLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldCodePostale, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DonnéesMagLayout.createSequentialGroup()
                        .addGroup(DonnéesMagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(44, 44, 44)
                        .addGroup(DonnéesMagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldFormeJuridique, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCapitale, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(120, 120, 120))
            .addGroup(DonnéesMagLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonValiderDonnéesMag, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DonnéesMagLayout.setVerticalGroup(
            DonnéesMagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DonnéesMagLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(DonnéesMagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldEnseigne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldNomRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DonnéesMagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTélephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DonnéesMagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldCodePostale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(DonnéesMagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldNoTVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldFormeJuridique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DonnéesMagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCapitale, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DonnéesMagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextFieldNoSIREN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DonnéesMagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNoSIRET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DonnéesMagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldCodeNAF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DonnéesMagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldNoRCF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(jButtonValiderDonnéesMag)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Données Magasin", DonnéesMag);

        ListeIdentifant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ListeIdentifant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeIdentifantActionPerformed(evt);
            }
        });

        jButtonAjoutUSER.setBackground(new java.awt.Color(102, 255, 102));
        jButtonAjoutUSER.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAjoutUSER.setText("Ajouter");
        jButtonAjoutUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutUSERActionPerformed(evt);
            }
        });

        jButtonModifUSER.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonModifUSER.setText("Modifier");
        jButtonModifUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifUSERActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Utilisateurs :");

        jButton5.setBackground(new java.awt.Color(102, 255, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Ajouter");

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setText("Modifier");

        jButton7.setBackground(new java.awt.Color(255, 51, 51));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setText("Supprimer");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel16.setText("Interface Utisateurs : ");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel17.setText("Interface Type Droits : ");

        jTextFieldIdentifiant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldIdentifiant.setEnabled(false);

        jPasswordFieldMDP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFieldMDP.setEnabled(false);

        ListeTypes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ListeTypes.setEnabled(false);
        ListeTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeTypesActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Identifiant :");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Mot de passe :");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Type de Droits");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 51, 51));
        jLabel21.setText("Attention : La suppréssion des comptes utilisateur est imposible");

        buttonGroup1.add(jRadioButtonActif);
        jRadioButtonActif.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButtonActif.setText("Actif");
        jRadioButtonActif.setEnabled(false);

        buttonGroup1.add(jRadioButtonInactif);
        jRadioButtonInactif.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButtonInactif.setText("Inactif");
        jRadioButtonInactif.setEnabled(false);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 51, 51));
        jLabel29.setText("SI le MDP est vide, il n'est pas mis à jour");

        javax.swing.GroupLayout CompteUSERLayout = new javax.swing.GroupLayout(CompteUSER);
        CompteUSER.setLayout(CompteUSERLayout);
        CompteUSERLayout.setHorizontalGroup(
            CompteUSERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompteUSERLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CompteUSERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CompteUSERLayout.createSequentialGroup()
                        .addGroup(CompteUSERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ListeIdentifant, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CompteUSERLayout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7))
                            .addComponent(jLabel16))
                        .addGap(5, 5, 5)
                        .addGroup(CompteUSERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addGroup(CompteUSERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CompteUSERLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CompteUSERLayout.createSequentialGroup()
                                .addComponent(jPasswordFieldMDP, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ListeTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56))
                    .addGroup(CompteUSERLayout.createSequentialGroup()
                        .addComponent(jButtonAjoutUSER)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModifUSER)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonActif, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonInactif)
                        .addGap(166, 166, 166)
                        .addComponent(jLabel21)
                        .addContainerGap())
                    .addGroup(CompteUSERLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CompteUSERLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(292, 292, 292))
        );
        CompteUSERLayout.setVerticalGroup(
            CompteUSERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CompteUSERLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(37, 37, 37)
                .addGroup(CompteUSERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(CompteUSERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListeIdentifant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldMDP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListeTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addGap(29, 29, 29)
                .addGroup(CompteUSERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CompteUSERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonInactif)
                        .addComponent(jRadioButtonActif))
                    .addGroup(CompteUSERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAjoutUSER)
                        .addComponent(jButtonModifUSER)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                .addGroup(CompteUSERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Compte Utilisateur", CompteUSER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1068, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Poste local", jPanel7);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Configuration Général");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderDonnéesMagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderDonnéesMagActionPerformed
        majInfoMag();
    }//GEN-LAST:event_jButtonValiderDonnéesMagActionPerformed

    private void ListeIdentifantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeIdentifantActionPerformed
        if(statutModifUSER == false && statutCréaUSER == false){
            idChoisi = ListeIdentifant.getSelectedIndex();
            String idType = "";
            try {
                PreparedStatement recupInfoUser = conn.prepareStatement("SELECT UA_Statut, UA_Identifiant, DroitUA_idDroitUA FROM UserApp WHERE iduser_app = ?");

                recupInfoUser.setString(1, identifiant[idChoisi][1]);

                ResultSet result = recupInfoUser.executeQuery();

                while(result.next()){
                    int statut = result.getInt("UA_Statut");
                    if (statut == 1){
                        jRadioButtonActif.setSelected(true);
                    }else{
                        jRadioButtonInactif.setSelected(true);
                    }
                    jTextFieldIdentifiant.setText(result.getString("UA_Identifiant"));
                    idType = result.getString("DroitUA_idDroitUA");
                }
                for (int i = 0; i < typeID.length; i++){
                    if (typeID[i][1].equals(idType)){
                        ListeTypes.setSelectedIndex(i);
                        break;
                    }
                }

                result.close();
                recupInfoUser.close();

            } catch (CommunicationsException e) {
                Bdd.lostCO(e);   
            } catch (SQLException ex) {
                Logger.getLogger(ConfigMachine.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ListeIdentifantActionPerformed

    private void jButtonModifUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifUSERActionPerformed
       if(statutModifUSER == false && statutCréaUSER == false){
           statutModifUSER = true;
           jTextFieldIdentifiant.setEnabled(true);
           jPasswordFieldMDP.setEnabled(true);
           ListeTypes.setEnabled(true);
           jRadioButtonActif.setEnabled(true);
           jRadioButtonInactif.setEnabled(true);
           jButtonModifUSER.setText("Valider modification");
           
           
        } else if (statutModifUSER == true && statutCréaUSER == false){
            statutModifUSER = false;
            jTextFieldIdentifiant.setEnabled(false);
            jPasswordFieldMDP.setEnabled(false);
            ListeTypes.setEnabled(false);
            jRadioButtonActif.setEnabled(false);
           jRadioButtonInactif.setEnabled(false);
            jButtonModifUSER.setText("Modifer");
            if (jPasswordFieldMDP.getText().equals("")){
                try {
                    String sql = "UPDATE UserApp SET UA_Statut=?, UA_Identifiant=?, DroitUA_idDroitUA=? WHERE iduser_app=?";
                    PreparedStatement majInfoUser = conn.prepareStatement(sql);

                    if(jRadioButtonActif.isSelected()){
                        majInfoUser.setInt(1, 1);
                    }else{
                        majInfoUser.setInt(1, 0);
                    }

                    majInfoUser.setString(2, jTextFieldIdentifiant.getText());
                    majInfoUser.setString(3, typeID[typeChoisi][1]);
                    majInfoUser.setString(4, identifiant[idChoisi][1]);

                    majInfoUser.execute();
                    majInfoUser.close();

                } catch (CommunicationsException e) {
                    Bdd.lostCO(e);
                } catch (SQLException ex) {
                    Logger.getLogger(ConfigMachine.class.getName()).log(Level.SEVERE, null, ex);
               }
            } else {
                try {
                    String sql = "UPDATE UserApp SET UA_Statut=?, UA_Identifiant=?, UA_MotDePasse=?, DroitUA_idDroitUA=? WHERE iduser_app=?";
                    PreparedStatement majInfoUser = conn.prepareStatement(sql);

                    if(jRadioButtonActif.isSelected()){
                        majInfoUser.setInt(1, 1);
                    }else{
                        majInfoUser.setInt(1, 0);
                    }
                    String passHash ;
                    passHash = hashage.Hash.hashPass(jPasswordFieldMDP.getText());

                    majInfoUser.setString(2, jTextFieldIdentifiant.getText());
                    majInfoUser.setString(3, passHash);
                    majInfoUser.setString(4, typeID[typeChoisi][1]);
                    majInfoUser.setString(5, identifiant[idChoisi][1]);

                    majInfoUser.execute();
                    majInfoUser.close();

                } catch (CommunicationsException e) {
                    Bdd.lostCO(e);
                } catch (SQLException | NoSuchAlgorithmException | UnsupportedEncodingException ex) {
                    Logger.getLogger(ConfigMachine.class.getName()).log(Level.SEVERE, null, ex);
               }
            }
            
        }
    }//GEN-LAST:event_jButtonModifUSERActionPerformed

    private void ListeTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeTypesActionPerformed
        typeChoisi = ListeTypes.getSelectedIndex();
    }//GEN-LAST:event_ListeTypesActionPerformed

    private void jButtonAjoutUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutUSERActionPerformed
        if(statutModifUSER == false && statutCréaUSER == false){
            statutCréaUSER = true;
            
            ListeIdentifant.setEnabled(false);
            ListeIdentifant.setSelectedIndex(-1);
            jTextFieldIdentifiant.setEnabled(true);
            jTextFieldIdentifiant.setText("");
            jPasswordFieldMDP.setEnabled(true);
            jPasswordFieldMDP.setText("");
            ListeTypes.setEnabled(true);
            jRadioButtonActif.setEnabled(true);
            jRadioButtonInactif.setEnabled(true);
            
        } else if(statutModifUSER == false && statutCréaUSER == true){
            statutCréaUSER = false;
            
            try {
                PreparedStatement ajoutUser = conn.prepareStatement("INSERT INTO UserApp(UA_Statut,UA_Identifiant,UA_MotDePasse,DroitUA_idDroitUA) values (?,?,?,?)");

                if(jRadioButtonActif.isSelected()){
                    ajoutUser.setInt(1, 1);
                }else{
                    ajoutUser.setInt(1, 0);
                }
                String passHash ;
                passHash = hashage.Hash.hashPass(jPasswordFieldMDP.getText());
                
                
                
                ajoutUser.setString(2, jTextFieldIdentifiant.getText());
                ajoutUser.setString(3, passHash);
                ajoutUser.setString(4, typeID[typeChoisi][1]);

                ajoutUser.execute();
                ajoutUser.close();
                
            } catch (CommunicationsException e) {
                Bdd.lostCO(e);
            } catch (SQLException ex) {
                Logger.getLogger(ConfigMachine.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(ConfigMachine.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(ConfigMachine.class.getName()).log(Level.SEVERE, null, ex);
            }
            ListeIdentifant.setModel(new DefaultComboBoxModel());
            recupIdUser();
            int i =0;
             while (identifiant[i][0] != null && i < identifiant.length){
                 ListeIdentifant.addItem(identifiant[i][0]);
                 i++;
             }
             ListeIdentifant.setSelectedIndex(0);
            
            jTextFieldIdentifiant.setEnabled(false);
            jPasswordFieldMDP.setEnabled(false);
            ListeTypes.setEnabled(false);
            ListeIdentifant.setEnabled(true);
            ListeIdentifant.setSelectedIndex(0);
            jRadioButtonActif.setEnabled(false);
            jRadioButtonInactif.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonAjoutUSERActionPerformed

    private void bValidIDclientCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValidIDclientCActionPerformed
        jDialogConfValidIDComptoir.setVisible(true);
    }//GEN-LAST:event_bValidIDclientCActionPerformed

    private void jButtonCSNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSNonActionPerformed
        jDialogConfValidIDComptoir.setVisible(false);
    }//GEN-LAST:event_jButtonCSNonActionPerformed

    private void jButtonCSOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSOuiActionPerformed
        try {
            String sql = "UPDATE Conf_G SET C_GidClientcomptoire=? WHERE idConf_G=?";
            PreparedStatement majIDcc = conn.prepareStatement(sql);
            majIDcc.setString(1, jTextFieldIdClientComptoir.getText());
            majIDcc.setInt(2, 1); // id in BDD
            
            majIDcc.execute();
            majIDcc.close();
            jDialogConfValidIDComptoir.setVisible(false); // on ferme la fenetre de configuration si tout est ok
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConfigMachine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCSOuiActionPerformed

    private void jButtonValiderDonnéesMag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderDonnéesMag1ActionPerformed
       try {
            String sql = "UPDATE Conf_G SET C_GeuroPts=? WHERE idConf_G=?";
            PreparedStatement majEuroPts = conn.prepareStatement(sql);
            majEuroPts.setString(1, jTextFieldRaportPTS.getText());
            majEuroPts.setInt(2, 1); // id in BDD
            
            majEuroPts.execute();
            majEuroPts.close();
            
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConfigMachine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonValiderDonnéesMag1ActionPerformed

    private void jButtonValiderDonnéesMag2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderDonnéesMag2ActionPerformed
        int i = 0;
        while(i < jTable1.getRowCount()){
            try {
                    String sql = "UPDATE PalierFid SET PF_ReducEuro=?, PF_PalierPts=? WHERE idPalierFid=?";
                    PreparedStatement majPalierFid = conn.prepareStatement(sql);
                    majPalierFid.setFloat(1, (float) jTable1.getValueAt(i, 2));
                    majPalierFid.setInt(2, (int) jTable1.getValueAt(i, 1));
                    majPalierFid.setInt(3, (int) jTable1.getValueAt(i, 0));

                    majPalierFid.execute();
                    majPalierFid.close();

                } catch (CommunicationsException e) {
                    Bdd.lostCO(e);
                } catch (SQLException ex) {
                    Logger.getLogger(ConfigMachine.class.getName()).log(Level.SEVERE, null, ex);
                }
            i++;
        }
    }//GEN-LAST:event_jButtonValiderDonnéesMag2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if(Données.getDUA_Admin() == 1){
            recupPalierR();
            try {
                UIManager.setLookAndFeel( new FlatLightLaf() );
            } catch( Exception ex ) {
                System.err.println( "Failed to initialize LaF" );
            }

            recupInfosMag();
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new ConfigMachine().setVisible(true);
                }
            });
        }else{
            ViolationDroit.main(null);
        }
        
    }
    
    public static void recupInfosMag(){
        try {
            Statement stateFA = conn.createStatement();
            ResultSet recupInfosMag = stateFA.executeQuery("SELECT * FROM Conf_Ets");
            

            while(recupInfosMag.next()){
                idConf_Ets = recupInfosMag.getString("idConf_Ets");
                C_EtsEnseigne = recupInfosMag.getString("C_EtsEnseigne");
                C_EtsTélephone = recupInfosMag.getString("C_EtsTélephone");
                C_EtsEmail = recupInfosMag.getString("C_EtsEmail");
                C_EtsNomRue = recupInfosMag.getString("C_EtsNomRue");
                C_EtsVille = recupInfosMag.getString("C_EtsVille");
                C_EtsCodePostal = recupInfosMag.getString("C_EtsCodePostal");
                C_EtsFormeJuridique = recupInfosMag.getString("C_EtsFormeJuridique");
                C_EtsCapitale = recupInfosMag.getString("C_EtsCapitale");
                C_EtsNoTVA = recupInfosMag.getString("C_EtsNoTVA");
                C_EtsNoSIREN = recupInfosMag.getString("C_EtsNoSIREN");
                C_EtsNoSIRET = recupInfosMag.getString("C_EtsNoSIRET");
                C_EtsCodeNAF = recupInfosMag.getString("C_EtsCodeNAF");
                C_EtsNoRCF = recupInfosMag.getString("C_EtsNoRCF");
                 
            }
            recupInfosMag.close();
            stateFA.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        }catch (SQLException ex){
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void majInfoMag(){
        try {
            String sql = "UPDATE Conf_Ets SET C_EtsEnseigne=?, C_EtsTélephone=?, C_EtsEmail=?, C_EtsNomRue=?, C_EtsVille=?, C_EtsCodePostal=?, C_EtsFormeJuridique=?, C_EtsCapitale=?, C_EtsNoTVA=?, C_EtsNoSIREN=?, C_EtsNoSIRET=?, C_EtsCodeNAF=?, C_EtsNoRCF=? WHERE idConf_Ets=?";
            PreparedStatement majInfoMag = conn.prepareStatement(sql);
            
            majInfoMag.setString(1, jTextFieldEnseigne.getText());
            majInfoMag.setString(2, jTextFieldTélephone.getText());
            majInfoMag.setString(3, jTextFieldEmail.getText());
            majInfoMag.setString(4, jTextFieldNomRue.getText());
            majInfoMag.setString(5, jTextFieldVille.getText());
            majInfoMag.setString(6, jTextFieldCodePostale.getText());
            majInfoMag.setString(7, jTextFieldFormeJuridique.getText());
            majInfoMag.setString(8, jTextFieldCapitale.getText());
            majInfoMag.setString(9, jTextFieldNoTVA.getText());
            majInfoMag.setString(10, jTextFieldNoSIREN.getText());
            majInfoMag.setString(11, jTextFieldNoSIRET.getText());
            majInfoMag.setString(12, jTextFieldCodeNAF.getText());
            majInfoMag.setString(13, jTextFieldNoRCF.getText());
            majInfoMag.setInt(14, 1); // id in BDD
            
            majInfoMag.execute();
            majInfoMag.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConfigMachine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static void recupIdUser(){
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT iduser_app, UA_Identifiant FROM UserApp");
            
            int i = 0;
            identifiant = new String[20][2];
            while(result.next()){
                identifiant[i][0] = result.getString("UA_Identifiant");
                identifiant[i][1] = result.getString("iduser_app");
                i++;
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public static void recupTypeID(){
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT idDroitUA, DUA_Type FROM DroitUA");
            
            int i = 0;
            while(result.next()){
                typeID[i][0] = result.getString("DUA_Type");
                typeID[i][1] = result.getString("idDroitUA");
                i++;
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public static void recupIDclientC(){
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT C_GidClientcomptoire FROM Conf_G");
            
            while(result.next()){
                idClientComptoir = result.getInt("C_GidClientcomptoire");
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
        public static void recupEuroPts(){
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT C_GeuroPts FROM Conf_G");
            
            while(result.next()){
                jTextFieldRaportPTS.setText(result.getString("C_GeuroPts"));
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private static int countPalierR(){ 
        int i = 0;
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT COUNT(*) FROM PalierFid");
            
            while(result.next()){
                i = result.getInt("COUNT(*)");
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return i;
    }
    
    private static void recupPalierR(){
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT * FROM PalierFid ORDER BY idPalierFid ASC");
            
            int i = 0;
            while(result.next()){
                int j=0;
                palierR[i][j++] = result.getInt("idPalierFid");
                palierR[i][j++] = result.getInt("PF_PalierPts");
                palierR[i][j++] = result.getFloat("PF_ReducEuro");
                i++;
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CompteUSER;
    private javax.swing.JPanel ConfigLogic;
    private javax.swing.JPanel DonnéesMag;
    private javax.swing.JComboBox<String> ListeIdentifant;
    private javax.swing.JComboBox<String> ListeTypes;
    private javax.swing.JLabel NomLogiciel;
    private javax.swing.JButton bValidIDclientC;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonAjoutUSER;
    private javax.swing.JButton jButtonCSNon;
    private javax.swing.JButton jButtonCSOui;
    private javax.swing.JButton jButtonModifUSER;
    private javax.swing.JButton jButtonValiderDonnéesMag;
    private javax.swing.JButton jButtonValiderDonnéesMag1;
    private javax.swing.JButton jButtonValiderDonnéesMag2;
    private javax.swing.JDialog jDialogConfValidIDComptoir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordFieldMDP;
    private javax.swing.JRadioButton jRadioButtonActif;
    private javax.swing.JRadioButton jRadioButtonInactif;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCapitale;
    private javax.swing.JTextField jTextFieldCodeNAF;
    private javax.swing.JTextField jTextFieldCodePostale;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEnseigne;
    private javax.swing.JTextField jTextFieldFormeJuridique;
    private javax.swing.JTextField jTextFieldIdClientComptoir;
    private javax.swing.JTextField jTextFieldIdentifiant;
    private javax.swing.JTextField jTextFieldNoRCF;
    private javax.swing.JTextField jTextFieldNoSIREN;
    private javax.swing.JTextField jTextFieldNoSIRET;
    private javax.swing.JTextField jTextFieldNoTVA;
    private javax.swing.JTextField jTextFieldNomRue;
    private static javax.swing.JTextField jTextFieldRaportPTS;
    private javax.swing.JTextField jTextFieldTélephone;
    private javax.swing.JTextField jTextFieldVille;
    // End of variables declaration//GEN-END:variables
}
