/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import com.formdev.flatlaf.FlatLightLaf;
import com.mysql.jdbc.exceptions.jdbc4.CommunicationsException;
import com.qoppa.pdfWriter.PDFPage;
import com.qoppa.pdfWriter.PDFDocument;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.io.File;
import java.io.IOException;
import static java.lang.Math.abs;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author neoag
 */
public class EntreesSorties extends javax.swing.JFrame {
    private static Connection conn = Bdd.coBdd();
    private static int nb_lignes;
    private static String[] fournisseur = new String[countFournisseur()];
    private static String[] motifES = new String[countMotifES()];
    
    private static int NbColonneTArticle = 6;
    private static Object[][] Article = new Object[countArticle()][NbColonneTArticle];
    private static String [] nomCloArticle = {"Code Barre", "Désignation", "Prix HT", "Stock actuel", "Quantité transaction", "idArticle"};
    private static int lignes_tab = 0;
    
    
    private static String  A_Designation;
    private static String A_CodeBarre;
    private static float A_PrixHT;
    private static int A_StockActu;
    private static int A_IDArticle;
    private static String A_Fournisseur;
    private static int A_QteTran;
    
    private static boolean qteValidée = true;
    private static boolean unicitéValidée = true;
    private static boolean etat;
    /**
     * Creates new form Entrée_Sortie
     */
    public EntreesSorties() {
        for (int i=0; i < Article.length; i++){
            for (int j = 0; j < NbColonneTArticle; j++) {
                Article[i][j] = null;
            }
        }
        lignes_tab=0;
        initComponents();
        
        URL iconURL = getClass().getResource(Données.getUrl_Logo());
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        jDialog1.setIconImage(icon.getImage());
        jDialog2.setIconImage(icon.getImage());
        jDialog3.setIconImage(icon.getImage());
        jDialog4.setIconImage(icon.getImage());
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        NomLogiciel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        NomLogiciel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        NomLogiciel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jDialog4 = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        NomLogiciel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        bouton_valider = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        NomLogiciel = new javax.swing.JLabel();
        boutton_suppr = new javax.swing.JButton();
        jComboBoxfournisseur = new javax.swing.JComboBox<>();
        code_barre_ajout = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bouton_ajouter = new javax.swing.JButton();
        jComboBoxmotifES = new javax.swing.JComboBox<>();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setTitle(Données.getNomLogiciel() + " | Erreur ");
        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(451, 310));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Erreur : Vous devez sélectionner un fournisseur et un motif");

        jPanel6.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel2.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel2.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel2.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(NomLogiciel2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel2)
                .addContainerGap())
        );

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jDialog2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog2.setTitle(Données.getNomLogiciel() + " | Erreur ");
        jDialog2.setResizable(false);
        jDialog2.setSize(new java.awt.Dimension(451, 310));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ne correspond pas au bon fournisseur");

        jPanel7.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel3.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel3.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel3.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(NomLogiciel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel3)
                .addContainerGap())
        );

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Erreur : L'article que vous essayez d'ajouter");

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jDialog3.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog3.setTitle(Données.getNomLogiciel() + " | Erreur ");
        jDialog3.setResizable(false);
        jDialog3.setSize(new java.awt.Dimension(451, 310));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("pour chaque article");

        jPanel8.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel4.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel4.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel4.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(NomLogiciel4, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel4)
                .addContainerGap())
        );

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Erreur : Vous devez renseigner une quantité de transaction");

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jDialog4.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog4.setTitle(Données.getNomLogiciel() + " | Erreur ");
        jDialog4.setResizable(false);
        jDialog4.setSize(new java.awt.Dimension(451, 310));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Erreur : Cet article est déja présent dans votre commande");

        jPanel9.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel5.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel5.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel5.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(NomLogiciel5, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel5)
                .addContainerGap())
        );

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDialog4Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog4Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Données.getNomLogiciel() + " | Entrées/Sorties ");
        setSize(new java.awt.Dimension(1920, 1080));

        bouton_valider.setText("VALIDER TRANSACTION");
        bouton_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_validerActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NomLogiciel.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel.setText(Données.getNomLogiciel());
        jPanel3.add(NomLogiciel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 1910, -1));

        boutton_suppr.setText("SUPPRIMER ARTICLE");
        boutton_suppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutton_supprActionPerformed(evt);
            }
        });

        jComboBoxfournisseur.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxfournisseur.setForeground(new java.awt.Color(0, 0, 0));
        int i = 0;
        while (fournisseur[i] != null && i < fournisseur.length){
            jComboBoxfournisseur.addItem(fournisseur[i]);
            i++;
        }
        jComboBoxfournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxfournisseurActionPerformed(evt);
            }
        });

        code_barre_ajout.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            Article,
            nomCloArticle) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }

        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(51, 153, 255));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(130, 244, 15));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        bouton_ajouter.setText("valider");
        bouton_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_ajouterActionPerformed(evt);
            }
        });

        jComboBoxmotifES.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxmotifES.setForeground(new java.awt.Color(0, 0, 0));
        int j = 0;
        while (motifES[j] != null && j < motifES.length){
            jComboBoxmotifES.addItem(motifES[j]);
            j++;
        }
        jComboBoxmotifES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxmotifESActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxfournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boutton_suppr, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(code_barre_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bouton_ajouter)))
                        .addGap(1313, 1313, 1313)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bouton_valider)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jComboBoxmotifES, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(code_barre_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bouton_ajouter)
                            .addComponent(jComboBoxmotifES, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxfournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boutton_suppr, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(bouton_valider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69))
        );

        jComboBoxfournisseur.setSelectedIndex(-1);
        jComboBoxmotifES.setSelectedIndex(-1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_ajouterActionPerformed
        if(jComboBoxfournisseur.getSelectedItem()==null || jComboBoxmotifES.getSelectedItem()==null){
            jDialog1.setVisible(true);
            jDialog1.setLocationRelativeTo(null);
        }
        else{
            for(int i = 0;i<lignes_tab;i++){
                if(code_barre_ajout.getText().equals(jTable1.getValueAt(i, 0).toString())){
                    unicitéValidée=false;
                }
            }
            if(unicitéValidée==true){
                recupArticleParCode(code_barre_ajout.getText());
                
            }else{
                jDialog4.setVisible(true);
                jDialog4.setLocationRelativeTo(null);
            }
            unicitéValidée=true;
        }
            
            

    }//GEN-LAST:event_bouton_ajouterActionPerformed

    private void boutton_supprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutton_supprActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for(int j = 0 ; j < NbColonneTArticle; j++){
            Article[jTable1.getSelectedRow()][j] = null;            
        }
        model.removeRow(jTable1.getSelectedRow());
        

        lignes_tab--;
    }//GEN-LAST:event_boutton_supprActionPerformed

    private void jComboBoxfournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxfournisseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxfournisseurActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jDialog1.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDialog2.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bouton_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_validerActionPerformed
        int compteur=0;
        for(int i=0;i<lignes_tab;i++){
            if(jTable1.getValueAt(i, 4)!=null){
                if(jTable1.getValueAt(i, 4).toString().equals("")){
                    compteur--;
                }else
                    compteur++;
            }
             
        }
        
        if(compteur==lignes_tab){
            qteValidée=true;
        }else
            qteValidée=false;
        
        if(jTable1.getValueAt(0, 0)==null){
            qteValidée=false;
        }
        
        
        if(qteValidée==true){
            for(int i =0;i<=lignes_tab;i++){
                Article[i][4] = jTable1.getValueAt(i, 4);
            }
            String sql = "select idFournisseur from Fournisseur where F_Nom = ?;";
            String sql_motif = "select idMotifES from MotifES where MES_Motif = ?;";
            String sql1 = "insert into EntrerSortie(ES_Date,ES_Heure,Fournisseur_idFournisseur,MotifES_idMotifES) values(current_date(),current_time(),?,?);";
            try {
                String fournisseur_choisi = jComboBoxfournisseur.getSelectedItem().toString();
                String motifES_choisi = jComboBoxmotifES.getSelectedItem().toString();
                PreparedStatement select_F = conn.prepareStatement(sql);
                select_F.setString(1, fournisseur_choisi);
                
                ResultSet resultFournisseur = select_F.executeQuery();
                
                int idFournisseur = 0;
                while(resultFournisseur.next()){
                 idFournisseur = resultFournisseur.getInt("idFournisseur");
                }
                select_F.close();
                
                PreparedStatement select_MES = conn.prepareStatement(sql_motif);
                select_MES.setString(1, motifES_choisi);
                
                ResultSet resultMotif = select_MES.executeQuery();
                
                int idMotif = 0;
                while(resultMotif.next()){
                 idMotif = resultMotif.getInt("idMotifES");
                }
                select_MES.close();
                PreparedStatement InsertES = conn.prepareStatement(sql1);
                InsertES.setInt(1, idFournisseur);
                InsertES.setInt(2, idMotif);
                InsertES.executeUpdate();
                InsertES.close();
                

            } catch (SQLException ex) {
                Logger.getLogger(EntreesSorties.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(etat==true){
                String sql_idMax = "Select max(idEntrerSortie) from EntrerSortie;";
                String sql_insertLigneES = "insert into LigneES(LES_Quantité,EntrerSortie_idEntrerSortie,TypeES_idTypeES,Article_idArticle) values(?,?,1,?);";
                String sql_updateQte = "update Article set A_Stock=A_Stock+?,A_DerniereES=current_date() where A_EAN=?;";
                try {
                    PreparedStatement maxID = conn.prepareStatement(sql_idMax);
                    ResultSet resultMaxID = maxID.executeQuery();
                    int idMax = 0;
                    while(resultMaxID.next()){
                        idMax = resultMaxID.getInt("max(idEntrerSortie)");
                    }
                    resultMaxID.close();
                    maxID.close();

                    PreparedStatement insertLigneES = conn.prepareStatement(sql_insertLigneES);
                    for(int i = 0;i<lignes_tab;i++){
                        insertLigneES.setInt(1, abs((int) Article[i][4]));
                        insertLigneES.setInt(2,idMax);
                        insertLigneES.setInt(3, (int) Article[i][5]);
                        insertLigneES.executeUpdate();
                    }
                    insertLigneES.close();

                    PreparedStatement updateQte = conn.prepareStatement(sql_updateQte);
                    for(int i = 0;i<lignes_tab;i++){
                        updateQte.setInt(1, abs((int) Article[i][4]));
                        updateQte.setString(2, (String) Article[i][0]);
                        updateQte.executeUpdate();
                    }
                    updateQte.close();




                } catch (SQLException ex) {
                    Logger.getLogger(EntreesSorties.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                String sql_idMax = "Select max(idEntrerSortie) from EntrerSortie;";
                String sql_insertLigneES = "insert into LigneES(LES_Quantité,EntrerSortie_idEntrerSortie,TypeES_idTypeES,Article_idArticle) values(?,?,2,?);";
                String sql_updateQte = "update Article set A_Stock=A_Stock-?,A_DerniereES=current_date() where A_EAN=?;";
                try {
                    PreparedStatement maxID = conn.prepareStatement(sql_idMax);
                    ResultSet resultMaxID = maxID.executeQuery();
                    int idMax = 0;
                    while(resultMaxID.next()){
                        idMax = resultMaxID.getInt("max(idEntrerSortie)");
                    }
                    resultMaxID.close();
                    maxID.close();

                    PreparedStatement insertLigneES = conn.prepareStatement(sql_insertLigneES);
                    for(int i = 0;i<lignes_tab;i++){
                        insertLigneES.setInt(1, abs((int) Article[i][4]));
                        insertLigneES.setInt(2,idMax);
                        insertLigneES.setInt(3, (int) Article[i][5]);
                        insertLigneES.executeUpdate();
                    }
                    insertLigneES.close();

                    PreparedStatement updateQte = conn.prepareStatement(sql_updateQte);
                    for(int i = 0;i<lignes_tab;i++){
                        updateQte.setInt(1, abs((int) Article[i][4]));
                        updateQte.setString(2, (String) Article[i][0]);
                        updateQte.executeUpdate();
                    }
                    updateQte.close();




                } catch (SQLException ex) {
                    Logger.getLogger(EntreesSorties.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int row_count = model.getRowCount();
            System.out.println("avant :"+row_count);
            for (int j = row_count-1; row_count>0; j--) {              
                
                    
                    if (jTable1.getValueAt(j, 0)==null) {
                        System.out.println("test");
                        jTable1.setRowSelectionInterval(j, j);
                        
                        
                        model.removeRow(jTable1.getSelectedRow());

                        row_count--;
                        lignes_tab--;
                        System.out.println("après chaque :"+row_count);
                        
                        
                    } else {
                        row_count=0;
                    }
                
            }
            
            jTable1.repaint();
            jTable1.revalidate();
            //-----------PDF-------------
            
            // on utilise l'heure actuelle pour changer le nom du récap
            //DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy-HH-mm-ss");  
            //LocalDateTime now = LocalDateTime.now();  
            //String dateStr = dtf.format(now);
            // On crée le panel qui sera mis dans la page pdf en y ajoutant des composants Swing
            JPanel page = new JPanel(new FlowLayout());
            page.setSize(1703, 2420);
            page.setVisible(true);
            page.setBackground(new java.awt.Color(255, 255, 255));
            
            JLabel label = new JLabel("Récapitulatif d'ES", SwingConstants.CENTER);
            label.setFont (label.getFont ().deriveFont (36.0f));
            label.setVisible(true);
            label.setSize(1703, 50);
            label.setLocation(15, 47);
            
            JTableHeader header = jTable1.getTableHeader();
            header.setLocation(50, 150);
            header.setFont(new Font("Arial", Font.BOLD, 24));
            header.setSize(1603,60);
 
            
            page.add(label);
            page.add(header);
            
            //int nbPages = (nbEti / 35)+1;
            /*int compteur_lignes = 0;
            int Ybase = 210;
            String[] columns = {"Code Barre","Désignation","Prix HT","Stock actuel","Quantité transaction","idArticle"};
            for (int j = 0; j < lignes_tab; j++) {              
                Object[][] data = {new Object[6]};
                for (int i = 0; i < 6; i++) {
                    if (jTable1.getValueAt(j, i).equals("")) {
                        break;
                    } else {
                        
                        data[0][i]=jTable1.getValueAt(j, i);
                    } 
                }
                JTable temp = new JTable(data,columns);
                temp.setModel(jTable1.getModel());
                temp.setLocation(50, Ybase);
                temp.setFont(new Font("Arial", Font.PLAIN, 24));
                temp.setSize(1603,60);
                temp.setShowGrid(false);
                temp.setShowHorizontalLines(true);
                temp.setGridColor(new java.awt.Color(190, 190, 190));
                temp.setRowHeight(60);
                Ybase+=60;
                page.add(temp);
                temp.setVisible(true);
                temp=null;
                data=null;

            }
            */
            
            
            
            
            
            
            jTable1.setLocation(50, 210);
            jTable1.setFont(new Font("Arial", Font.PLAIN, 24));
            jTable1.setSize(1603,2120);
            jTable1.setShowGrid(false);
            jTable1.setShowHorizontalLines(true);
            jTable1.setGridColor(new java.awt.Color(190, 190, 190));
            
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment( JLabel.CENTER );
            for(int i = 0; i<6; i++) {
                jTable1.getColumnModel().getColumn(i).setCellRenderer( centerRenderer );
            }
            jTable1.setRowHeight(60);
            
            
            
            
            page.add(jTable1);
            
            //On crée la page pdf elle-même
            Paper p = new Paper();
            p.setSize(8.25 * 72, 11.75 * 72);
            p.setImageableArea(0, 0, 8.25 * 72, 11.75 * 72);
            PageFormat pf = new PageFormat();
            pf.setPaper(p);
            PDFDocument pdfDoc = new PDFDocument();
            // Create page
            PDFPage pagePDF = pdfDoc.createPage(pf);

            // Add page to document
            pdfDoc.addPage(pagePDF);
            // get graphics object from the page
            Graphics2D g2d = pagePDF.createGraphics();
            g2d.scale(0.35, 0.35);
            // myComponent being a JComponent showing on the screen
            page.print(g2d);
            
            
            File outFile = new File("temp/recap.pdf");

            // save document
            try {
                pdfDoc.saveDocument(outFile.getAbsolutePath());
            } catch (IOException ex) {
                Logger.getLogger(Etiquettes.class.getName()).log(Level.SEVERE, null, ex);
            }

            extend.ouvrirPDF.ouvrirDocPdf("temp/recap.pdf");    
        }else if(qteValidée==false){ 

            jDialog3.setVisible(true);
            jDialog3.setLocationRelativeTo(null);
        }
        
        dispose();
        
        
        
        
        
        
    }//GEN-LAST:event_bouton_validerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jDialog3.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jDialog4.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBoxmotifESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxmotifESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxmotifESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], boolean etatParam) {
        if(Données.getDUA_AchatVente()== 1){
            etat = etatParam;
            System.out.println(etat);
            
                
            recupMotifES();
            recupFournisseur();
            try {
                UIManager.setLookAndFeel( new FlatLightLaf() );
            } catch( Exception ex ) {
                System.err.println( "Failed to initialize LaF" );
            }

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new EntreesSorties().setVisible(true);
                }
            });
        }else
            ViolationDroit.main(null);
        

    }
     private static int countFournisseur(){ 
        int i = 0;
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT COUNT(*) FROM Fournisseur");
            
            while(result.next()){
                i = result.getInt("COUNT(*)");
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return i+1;
    }
    
    public static void recupFournisseur(){
        try {
            Statement state = conn.createStatement();
            ResultSet recupFournisseur = state.executeQuery("SELECT F_Nom FROM Fournisseur");
            
            int i = 0;
            while(recupFournisseur.next()){
                fournisseur[i] = recupFournisseur.getString("F_Nom");
                i++;
            }
            recupFournisseur.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

     private static int countMotifES(){ 
        int i = 0;
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT COUNT(*) FROM MotifES");
            
            while(result.next()){
                i = result.getInt("COUNT(*)");
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return i+1;
    }
    
    public static void recupMotifES(){
        try {
            Statement state = conn.createStatement();
            ResultSet recupMotif = state.executeQuery("SELECT MES_Motif FROM MotifES");
            
            int i = 0;
            while(recupMotif.next()){
                motifES[i] = recupMotif.getString("MES_Motif");
                i++;
            }
            recupMotif.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private static int countArticle(){ 
        int i = 0;
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT COUNT(*) FROM Article");
            
            while(result.next()){
                i = result.getInt("COUNT(*)");
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return i;
    }
    public static void recupArticleParCode(String codeBarre){
        String sql = "SELECT idArticle, A_Designation, A_PrixAchat,  A_Stock,Fournisseur.F_Nom\n" +
                    "FROM `Article` \n" +
                    "INNER JOIN Fournisseur on Article.Fournisseur_idFournisseur = Fournisseur.idFournisseur\n" +
                    "WHERE A_EAN = ?";
        try {
            PreparedStatement RecupInfoArticle = conn.prepareStatement(sql);
            RecupInfoArticle.setDouble(1,Double.parseDouble(codeBarre) );
            ResultSet result = RecupInfoArticle.executeQuery();
            while(result.next()){
                A_Designation = result.getString("A_Designation");
                A_Fournisseur = result.getString("Fournisseur.F_Nom");
                A_PrixHT = result.getFloat("A_PrixAchat");
                A_IDArticle = result.getInt("idArticle");
                A_StockActu = result.getInt("A_Stock");
                }
            
            if (A_Fournisseur.equals(jComboBoxfournisseur.getSelectedItem().toString())){
                Article[lignes_tab][0] = codeBarre;
                jTable1.setValueAt(codeBarre,lignes_tab, 0);
                jComboBoxfournisseur.setEnabled(false);
                jComboBoxmotifES.setEnabled(false);
                jTable1.setValueAt(A_Designation,lignes_tab, 1); //numero de ligne, numero de colonne
                Article[lignes_tab][1] = A_Designation;
                jTable1.setValueAt(A_PrixHT,lignes_tab,2);
                Article[lignes_tab][2] = A_PrixHT;
                jTable1.setValueAt(A_StockActu,lignes_tab,3);
                Article[lignes_tab][3] = A_StockActu;
                jTable1.setValueAt(A_IDArticle,lignes_tab,5);
                Article[lignes_tab][5] = A_IDArticle;
                lignes_tab++;
            }
            else{
                jDialog2.setVisible(true);
                jDialog2.setLocationRelativeTo(null);
            }

                result.close();
                RecupInfoArticle.close();
        } catch (SQLException ex) {
            Logger.getLogger(EntreesSorties.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomLogiciel;
    private javax.swing.JLabel NomLogiciel2;
    private javax.swing.JLabel NomLogiciel3;
    private javax.swing.JLabel NomLogiciel4;
    private javax.swing.JLabel NomLogiciel5;
    private javax.swing.JButton bouton_ajouter;
    private javax.swing.JButton bouton_valider;
    private javax.swing.JButton boutton_suppr;
    private javax.swing.JTextField code_barre_ajout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private static javax.swing.JComboBox<String> jComboBoxfournisseur;
    private static javax.swing.JComboBox<String> jComboBoxmotifES;
    private javax.swing.JDialog jDialog1;
    private static javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
