/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import com.formdev.flatlaf.FlatLightLaf;
import com.mysql.jdbc.exceptions.jdbc4.CommunicationsException;
import extend.UserListCellRenderer;
import java.awt.Graphics;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author etien
 */
public class FichierFournisseur extends javax.swing.JFrame {
    
    private static Connection conn = Bdd.coBdd(); //Instanciation de la variable de connexion à la base de données

    private static int NbColonneTfournisseur = 4;
    private static Object[][] Fournisseur = new Object[countFournisseur()][NbColonneTfournisseur];
    private static String [] nomColFournisseur = { "Code Fournisseur", "Nom", "Telephone", "Email"};
      
    
    private static int idFournisseurSelect = 0;
    private static int idLigneSelect;
    private static int idLigneAModif;
    
    private static boolean statutModif = false;
    private static boolean statutCréa = false;
    private static boolean ErreurCréa = false;
    
    private static String F_CodeFournisseur;
    private static String F_Nom;
    private static String F_Email;
    private static String F_Adresse;
    private static String F_CodePostale;
    private static String F_Ville;
    private static String F_Tel;

    
    /**
     * Creates new form FichierArticle
     */
    public FichierFournisseur() {
        initComponents();
        URL iconURL = getClass().getResource(Données.getUrl_Logo());
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        confirmSupp.setIconImage(icon.getImage());
        erreurSupprFournisseur.setIconImage(icon.getImage());
        confirmSupp.setLocationRelativeTo(this);
        erreurSupprFournisseur.setLocationRelativeTo(this);
        
        setExtendedState(JFrame.MAXIMIZED_BOTH); // ouverture de la fenetre en full screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmSupp = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jButtonCSNon = new javax.swing.JButton();
        jButtonCSOui = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        erreurSupprFournisseur = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jButtonErreurFermer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        NomLogiciel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        NomLogiciel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelCodeBar = new javax.swing.JLabel();
        jTextFieldAdresse = new javax.swing.JTextField();
        jLabelNom = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jButtonSuprimer = new javax.swing.JButton();
        jButtonCreer = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jTextFieldCodeFournisseur = new javax.swing.JTextField();
        jTextFieldVille = new javax.swing.JTextField();
        jTextFieldCP = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldTel = new javax.swing.JTextField();
        jLabelNom1 = new javax.swing.JLabel();
        jLabelNom2 = new javax.swing.JLabel();
        jLabelNom3 = new javax.swing.JLabel();
        jLabelPrénom1 = new javax.swing.JLabel();
        jLabelPrénom2 = new javax.swing.JLabel();
        ErreurLabel = new javax.swing.JLabel();

        confirmSupp.setTitle(Données.getNomLogiciel() + " | confirmation de suppression");
        confirmSupp.setAlwaysOnTop(true);
        confirmSupp.setMinimumSize(new java.awt.Dimension(400, 219));
        confirmSupp.setResizable(false);
        confirmSupp.setSize(new java.awt.Dimension(400, 176));

        jPanel4.setMinimumSize(new java.awt.Dimension(400, 219));

        jButtonCSNon.setText("NON");
        jButtonCSNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSNonActionPerformed(evt);
            }
        });

        jButtonCSOui.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCSOui.setText("OUI");
        jButtonCSOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSOuiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Etes-vous sûr de vouloir supprimer cette fiche Fournisseur ?");

        jPanel7.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(Données.getNomLogiciel() + " | Connexion ");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jButtonCSOui, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButtonCSNon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCSNon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCSOui, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout confirmSuppLayout = new javax.swing.GroupLayout(confirmSupp.getContentPane());
        confirmSupp.getContentPane().setLayout(confirmSuppLayout);
        confirmSuppLayout.setHorizontalGroup(
            confirmSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        confirmSuppLayout.setVerticalGroup(
            confirmSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        erreurSupprFournisseur.setTitle(Données.getNomLogiciel() + " | Erreur de suppression");
        erreurSupprFournisseur.setAlwaysOnTop(true);
        erreurSupprFournisseur.setIconImage(null);
        erreurSupprFournisseur.setMinimumSize(new java.awt.Dimension(400, 234));
        erreurSupprFournisseur.setResizable(false);
        erreurSupprFournisseur.setSize(new java.awt.Dimension(400, 176));

        jPanel5.setMinimumSize(new java.awt.Dimension(400, 234));

        jButtonErreurFermer.setText("Fermer");
        jButtonErreurFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonErreurFermerActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("achat a déjà été réalisé !");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Erreur : La suppression est impossible car un  ");

        jPanel6.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel1.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel1.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NomLogiciel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButtonErreurFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jButtonErreurFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout erreurSupprFournisseurLayout = new javax.swing.GroupLayout(erreurSupprFournisseur.getContentPane());
        erreurSupprFournisseur.getContentPane().setLayout(erreurSupprFournisseurLayout);
        erreurSupprFournisseurLayout.setHorizontalGroup(
            erreurSupprFournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        erreurSupprFournisseurLayout.setVerticalGroup(
            erreurSupprFournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Données.getNomLogiciel() + " | Fichier Fournisseurs ");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        UserListCellRenderer cellRenderer = new UserListCellRenderer();
        jTable1.setDefaultRenderer(Object.class, cellRenderer);
        jTable1.setDefaultRenderer(Double.class, cellRenderer);
        jTable1.setDefaultRenderer(Integer.class, cellRenderer);
        jTable1.setDefaultRenderer(Float.class, cellRenderer);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            Fournisseur,
            nomColFournisseur) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            boolean[] canEdit = new boolean [] {
                false,false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(51, 153, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(130, 244, 15));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(150);

        }

        jPanel3.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(NomLogiciel, javax.swing.GroupLayout.PREFERRED_SIZE, 1917, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomLogiciel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Fichier Fournisseur");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Fournisseur selectionné :");

        jPanel2.setPreferredSize(new java.awt.Dimension(1800, 332));

        jLabelCodeBar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCodeBar.setText("Code Fournisseur");

        jTextFieldAdresse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldAdresse.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldAdresse.setEnabled(false);

        jLabelNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNom.setText("Nom");

        jTextFieldNom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNom.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNom.setEnabled(false);

        jButtonSuprimer.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSuprimer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonSuprimer.setText("Supprimer *");
        jButtonSuprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuprimerActionPerformed(evt);
            }
        });

        jButtonCreer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonCreer.setText("Créer fournisseur");
        jButtonCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerActionPerformed(evt);
            }
        });

        jButtonModifier.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jTextFieldCodeFournisseur.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldCodeFournisseur.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCodeFournisseur.setEnabled(false);

        jTextFieldVille.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldVille.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldVille.setEnabled(false);

        jTextFieldCP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldCP.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCP.setEnabled(false);

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldEmail.setEnabled(false);

        jTextFieldTel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldTel.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldTel.setEnabled(false);

        jLabelNom1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNom1.setText("Adresse");

        jLabelNom2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNom2.setText("Ville");

        jLabelNom3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNom3.setText("Code Postal");

        jLabelPrénom1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrénom1.setText("Email");

        jLabelPrénom2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrénom2.setText("Téléphone");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNom3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelNom2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(268, 268, 268))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelPrénom1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCodeFournisseur, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jLabelCodeBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonModifier)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreer)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSuprimer)))
                .addContainerGap(771, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(713, 713, 713)
                    .addComponent(jLabelPrénom2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1072, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCodeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodeFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNom2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNom3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelPrénom1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonCreer)
                    .addComponent(jButtonSuprimer))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(190, Short.MAX_VALUE)
                    .addComponent(jLabelPrénom2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(120, 120, 120)))
        );

        ErreurLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ErreurLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1886, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(ErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        ErreurLabel.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        
        if (statutModif == false && statutCréa == false && idFournisseurSelect != 0){
            idLigneAModif = idLigneSelect;
            statutModif = true;
            jButtonModifier.setText("Valider");
            jButtonModifier.setBackground(new java.awt.Color(53, 219, 73));
            
            jTextFieldNom.setEnabled(true);
            jTextFieldAdresse.setEnabled(true);
            jTextFieldCP.setEnabled(true);
            jTextFieldEmail.setEnabled(true);
            jTextFieldVille.setEnabled(true);
            jTextFieldTel.setEnabled(true);
            
        }else if (statutModif == true && statutCréa == false){
            try {
                statutModif = false;
                System.out.println("valider");
                LocalDate localDate = LocalDate.now();

                String sql = "UPDATE Fournisseur SET F_Nom = UPPER(?), F_Email=?, F_Adresse = ?, F_CodePostale = ?, F_Ville = ?, F_Tel = ? WHERE idFournisseur = ?";
                PreparedStatement modifFournisseur = conn.prepareStatement(sql);


                modifFournisseur.setString(1, jTextFieldNom.getText());
                modifFournisseur.setString(2, jTextFieldEmail.getText());
                modifFournisseur.setString(3, jTextFieldAdresse.getText());
                modifFournisseur.setString(4, jTextFieldCP.getText());
                modifFournisseur.setString(5, jTextFieldVille.getText());
                modifFournisseur.setString(6, jTextFieldTel.getText());

                modifFournisseur.setInt(7, idFournisseurSelect);
                modifFournisseur.execute();
                modifFournisseur.close();

                jButtonModifier.setText("Modfier");
                jButtonModifier.setBackground(new java.awt.Color(210, 210, 210));
                
                jTextFieldNom.setEnabled(false);
                jTextFieldAdresse.setEnabled(false);
                jTextFieldCP.setEnabled(false);
                jTextFieldEmail.setEnabled(false);
                jTextFieldVille.setEnabled(false);
                jTextFieldTel.setEnabled(false);

                Fournisseur[idLigneAModif][2] = jTextFieldNom.getText();
                jTable1.setValueAt(jTextFieldNom.getText(), idLigneAModif, 1);
                jTable1.setValueAt(jTextFieldTel.getText(), idLigneAModif, 2);
                jTable1.setValueAt(jTextFieldEmail.getText(), idLigneAModif, 3);
                //finir la maj du tableau avec les infos quon a rentées

            } catch (CommunicationsException e) {
                Bdd.lostCO(e);    
            } catch (SQLException ex) {
                ErreurLabel.setText("Vous devez saisir des valeurs correctes ! Erreur : " + ex.getMessage());
            }
            
            
        }else{
            System.out.println("erreur");
        }
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String idFournisseurSelect_s = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString(); // 0 pour idF
        idFournisseurSelect = Integer.parseInt(idFournisseurSelect_s);
        //System.err.println(idFournisseurSelect);
        idLigneSelect = jTable1.getSelectedRow();
        
        
        try {
            if (statutModif == false && statutCréa == false && ErreurCréa == false){
                String sql = "SELECT * FROM `Fournisseur` WHERE idFournisseur = ?";
                PreparedStatement RecupInfoFournisseurs = conn.prepareStatement(sql);

                RecupInfoFournisseurs.setInt(1, idFournisseurSelect);
                ResultSet result = RecupInfoFournisseurs.executeQuery();

                while(result.next()){
                    F_CodeFournisseur = result.getString("idFournisseur");
                    F_Nom = result.getString("F_Nom");
                    F_Email = result.getString("F_Email");
                    F_Adresse = result.getString("F_Adresse");
                    F_CodePostale = result.getString("F_CodePostale");
                    F_Ville = result.getString("F_Ville");
                    F_Tel = result.getString("F_Tel");
                }

                result.close();
                RecupInfoFournisseurs.close();
                jTextFieldCodeFournisseur.setText(F_CodeFournisseur);
                jTextFieldCodeFournisseur.setEnabled(false);
                jTextFieldAdresse.setText(F_Adresse);
                jTextFieldAdresse.setEnabled(false);
                jTextFieldCP.setText(F_CodePostale);
                jTextFieldCP.setEnabled(false);
                jTextFieldEmail.setText(F_Email);
                jTextFieldEmail.setEnabled(false);
                jTextFieldNom.setText(F_Nom);
                jTextFieldNom.setEnabled(false);
                jTextFieldTel.setText(F_Tel);
                jTextFieldTel.setEnabled(false);
                jTextFieldVille.setText(F_Ville);
                jTextFieldVille.setEnabled(false);
                
                
            }
            
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(FichierFournisseur.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonSuprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuprimerActionPerformed
        if(statutCréa == false && statutModif == false && idFournisseurSelect != 0){
            confirmSupp.setVisible(true);
        }
    }//GEN-LAST:event_jButtonSuprimerActionPerformed

    private void jButtonCSOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSOuiActionPerformed
        if (statutCréa == false && statutModif == false && idFournisseurSelect != 0){

            String nbDeTicketFournisseur="0";
            String nbArticlesFournisseur="0";
            
            int idFournisseurSelect_copie = idFournisseurSelect;
            int idLigneSelect_copie = idLigneSelect;
            try {
                String sql = "SELECT count(*) FROM EntrerSortie WHERE Fournisseur_idFournisseur = ?";
                PreparedStatement verifHistoriqueT = conn.prepareStatement(sql);
                verifHistoriqueT.setInt(1, idFournisseurSelect_copie);
                
                ResultSet result = verifHistoriqueT.executeQuery();
            
                while(result.next()){
                    nbDeTicketFournisseur = result.getString("count(*)");
                }
                
                verifHistoriqueT.execute();
                verifHistoriqueT.close();
                
            } catch (CommunicationsException e) {
                Bdd.lostCO(e);
            } catch (SQLException ex) {
                Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                String sql = "SELECT count(*) FROM Article WHERE Fournisseur_idFournisseur = ?";
                PreparedStatement verifHistoriqueT = conn.prepareStatement(sql);
                verifHistoriqueT.setInt(1, idFournisseurSelect_copie);
                
                ResultSet result = verifHistoriqueT.executeQuery();
            
                while(result.next()){
                    nbArticlesFournisseur = result.getString("count(*)");
                }
                
                verifHistoriqueT.execute();
                verifHistoriqueT.close();
                
            } catch (CommunicationsException e) {
                Bdd.lostCO(e);
            } catch (SQLException ex) {
                Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(nbDeTicketFournisseur.equals("0") && nbArticlesFournisseur.equals("0")){
                try {
                    String sql = "DELETE FROM Fournisseur WHERE idFournisseur = ?";
                    PreparedStatement suppFournisseur = conn.prepareStatement(sql);
                    suppFournisseur.setInt(1, idFournisseurSelect_copie);
                
                    suppFournisseur.execute();
                    suppFournisseur.close();
                    confirmSupp.setVisible(false);
                    
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.removeRow(idLigneSelect_copie);
                    // ATTENTION il faut supriler le client dans le tableau  
                    
                } catch (CommunicationsException e) {
                    Bdd.lostCO(e);
                } catch (SQLException ex) {
                    Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                confirmSupp.setVisible(false);
                erreurSupprFournisseur.setVisible(true);
                //je ne supprime pas le client car vente réalisée
            }
            
        }
    }//GEN-LAST:event_jButtonCSOuiActionPerformed

    private void jButtonCSNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSNonActionPerformed
        confirmSupp.setVisible(false);
    }//GEN-LAST:event_jButtonCSNonActionPerformed

    private void jButtonCreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerActionPerformed
        if(statutCréa == false && statutModif == false ){
            if(ErreurCréa == false){
                statutCréa = true;
                
                jButtonCreer.setText("Valider");
                ErreurLabel.setText("");
                jButtonCreer.setBackground(new java.awt.Color(53, 219, 73));
                idFournisseurSelect = 0;
                jTextFieldAdresse.setEnabled(true);
                jTextFieldAdresse.setText("");
                jTextFieldNom.setEnabled(true);
                jTextFieldNom.setText("");

                jTextFieldVille.setEnabled(true);
                jTextFieldVille.setText("");
                jTextFieldCP.setEnabled(true);
                jTextFieldCP.setText("");

                jTextFieldTel.setEnabled(true);
                jTextFieldTel.setText("");
                jTextFieldEmail.setEnabled(true);
                jTextFieldEmail.setText("");

                jTextFieldCodeFournisseur.setText("");
                jTextFieldCodeFournisseur.setEnabled(false);
                
                
                
            }else{
                ErreurCréa =false;
                statutCréa = true;
                jButtonCreer.setText("Valider");
                ErreurLabel.setText("");
                jButtonCreer.setBackground(new java.awt.Color(53, 219, 73));
                idFournisseurSelect = 0;
            }
            
            
            
        }else if (statutCréa == true && statutModif == false && idFournisseurSelect == 0){

            statutCréa = false;
            jButtonCreer.setText("Créer Client");
            jButtonCreer.setBackground(new java.awt.Color(210, 210, 210));
            ErreurLabel.setText("");
            
            try {
                String sql;

                sql = "INSERT INTO Fournisseur (F_Nom, F_Adresse, F_CodePostale, F_Ville, F_Email, F_Tel) VALUES (?,?,?,?,?,?)";
                
                PreparedStatement creerFournisseur = conn.prepareStatement(sql);
                
                                
                creerFournisseur.setString(1, jTextFieldNom.getText());
                creerFournisseur.setString(2,jTextFieldAdresse.getText());
                creerFournisseur.setString(3, jTextFieldCP.getText());
                creerFournisseur.setString(4,jTextFieldVille.getText());
                creerFournisseur.setString(5,jTextFieldEmail .getText()); 
                creerFournisseur.setString(6,jTextFieldTel.getText());  
                
                creerFournisseur.execute();
                creerFournisseur.close();
                
                int lastIdFournisseur;
                Statement state = conn.createStatement();
                ResultSet result = state.executeQuery("SELECT idFournisseur FROM Fournisseur ORDER BY idFournisseur DESC LIMIT 1");
                
                while(result.next()){
                    jTextFieldCodeFournisseur.setText(result.getString("idFournisseur"));
                }
                result.close();
                state.close();
                
                ErreurLabel.setText("");
                
                
                jTextFieldNom.setEnabled(false);
                jTextFieldAdresse.setEnabled(false);
                jTextFieldCP.setEnabled(false);
                jTextFieldEmail.setEnabled(false);
                jTextFieldVille.setEnabled(false);
                jTextFieldTel.setEnabled(false);
                
                //ajout dans la table courante
                int nbLigne = jTable1.getRowCount();
                Fournisseur = new Object[countFournisseur()][NbColonneTfournisseur];
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(new Object[]{jTextFieldCodeFournisseur.getText(), jTextFieldNom.getText(), jTextFieldTel.getText(), jTextFieldEmail.getText() });

                
            } catch (CommunicationsException e) {
                Bdd.lostCO(e);
            } catch (SQLException ex) {
                ErreurLabel.setText("Vous devez saisir des valeurs correctes ! Erreur : " + ex.getMessage());
            }catch (NumberFormatException e){
                ErreurLabel.setText("Vous devez saisir des valeurs correctes ! Erreur : " + e.getMessage());
                ErreurCréa = true;
                jButtonCreer.setText("Corriger");
                jButtonCreer.setBackground(new java.awt.Color(249, 194, 78));
            }
        }
    }//GEN-LAST:event_jButtonCreerActionPerformed

    private void jButtonErreurFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonErreurFermerActionPerformed
        erreurSupprFournisseur.setVisible(false);
    }//GEN-LAST:event_jButtonErreurFermerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if(Données.getDUA_FichierClient()== 1){
           
            recupFournisseur();
            ErreurCréa = false;
            statutCréa = false;
            statutModif = false;
            
            
            try {
                UIManager.setLookAndFeel( new FlatLightLaf() );
            } catch( Exception ex ) {
                System.err.println( "Failed to initialize LaF" );
            }

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FichierFournisseur().setVisible(true);
                }
            });
            
        }else{
            ViolationDroit.main(null);
        }
    }
    
    private static int countFournisseur(){ 
        int i = 0;
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT COUNT(*) FROM Fournisseur");
            
            while(result.next()){
                i = result.getInt("COUNT(*)");
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return i;
    }
    
    private static void recupFournisseur(){
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT idFournisseur, F_Nom, F_Tel, F_Email FROM Fournisseur ORDER BY `F_Nom` ASC");
            
            int i = 0;
            while(result.next()){
                int j=0;
                Fournisseur[i][j++] = result.getInt("idFournisseur");
                Fournisseur[i][j++] = result.getString("F_Nom");
                Fournisseur[i][j++] = result.getString("F_Tel");
                Fournisseur[i][j++] = result.getString("F_Email");
                i++;
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErreurLabel;
    private javax.swing.JLabel NomLogiciel;
    private javax.swing.JLabel NomLogiciel1;
    private javax.swing.JDialog confirmSupp;
    private javax.swing.JDialog erreurSupprFournisseur;
    private javax.swing.JButton jButtonCSNon;
    private javax.swing.JButton jButtonCSOui;
    private javax.swing.JButton jButtonCreer;
    private javax.swing.JButton jButtonErreurFermer;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSuprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCodeBar;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNom1;
    private javax.swing.JLabel jLabelNom2;
    private javax.swing.JLabel jLabelNom3;
    private javax.swing.JLabel jLabelPrénom1;
    private javax.swing.JLabel jLabelPrénom2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldCodeFournisseur;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldTel;
    private javax.swing.JTextField jTextFieldVille;
    // End of variables declaration//GEN-END:variables
}
