/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import com.formdev.flatlaf.FlatLightLaf;
import com.mysql.jdbc.exceptions.jdbc4.CommunicationsException;
import extend.UserListCellRenderer;
import java.awt.Graphics;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author etien
 */
public class FichierArticle extends javax.swing.JFrame {
    
    private static Connection conn = Bdd.coBdd(); //Instanciation de la variable de connexion à la base de données

    private static int NbColoneTArticle = 7;
    private static Object[][] Article = new Object[countArticle()][NbColoneTArticle];
    private static String [] nomCloArticle = { "Statut", "Code Barre", "Désignation", "Prix de vente", "Stock", "Derniere vente", "idArticle"};
    
    private static String[] fournisseur = new String[countFournisseur()]; 
    private static String[] TVA = new String[countTVA()]; 
    private static String[] familleArticle = new String[countFamilleArticle()];
    
    private static int idArticleSelect = 0;
    private static int idLigneSelect;
    private static int idLigneAModif;
    private static int idArticleAModif;
    
    private static boolean statutModif = false;
    private static boolean statutCréa = false;
    private static boolean ErreurCréa = false;
    
    private static int A_statut;
    private static String A_Designation;
    private static String A_EAN;
    private static String A_PrixAchat;
    private static String A_Marge;
    private static String A_PrixDeVente;
    private static String A_Stock;
    private static String A_StockAlerte;
    private static String A_DateCréa;
    private static String A_DateModif;
    private static String A_DerniereVente;
    private static String FA_Nom;
    private static String F_Nom;
    private static String TVA_Taux;

    
    /**
     * Creates new form FichierArticle
     */
    public FichierArticle() {
        initComponents();
        URL iconURL = getClass().getResource(Données.getUrl_Logo());
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        confirmSupp.setIconImage(icon.getImage());
        erreurSupprArticle.setIconImage(icon.getImage());
        confirmSupp.setLocationRelativeTo(this);
        erreurSupprArticle.setLocationRelativeTo(this);
        
        setExtendedState(JFrame.MAXIMIZED_BOTH); // ouverture de la fenetre en full screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupActifInactif = new javax.swing.ButtonGroup();
        confirmSupp = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jButtonCSNon = new javax.swing.JButton();
        jButtonCSOui = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        buttonGroupCalculPrix = new javax.swing.ButtonGroup();
        erreurSupprArticle = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jButtonErreurFermer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        NomLogiciel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        NomLogiciel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelCodeBar = new javax.swing.JLabel();
        jTextFieldCodeBar = new javax.swing.JTextField();
        jLabelDesignation = new javax.swing.JLabel();
        jTextFieldDesignation = new javax.swing.JTextField();
        jLabelStock = new javax.swing.JLabel();
        jTextFieldStock = new javax.swing.JTextField();
        jLabelDerniereVente = new javax.swing.JLabel();
        jTextFieldDernierVente = new javax.swing.JTextField();
        jLabelDernierModif = new javax.swing.JLabel();
        jTextFieldDerniereModif = new javax.swing.JTextField();
        jLabelPrixAchat = new javax.swing.JLabel();
        jTextFieldPrixArchat = new javax.swing.JTextField();
        jLabelMarge = new javax.swing.JLabel();
        jTextFieldMarge = new javax.swing.JTextField();
        jLabelTVA = new javax.swing.JLabel();
        jLabelPrixDeVente = new javax.swing.JLabel();
        jTextFieldPrixDeVente = new javax.swing.JTextField();
        jLabelFournisseur = new javax.swing.JLabel();
        jLabelFamilleArticle = new javax.swing.JLabel();
        jTextFieldDateCreation = new javax.swing.JTextField();
        jButtonSuprimer = new javax.swing.JButton();
        jButtonCreer = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jRadioButtonActif = new javax.swing.JRadioButton();
        jRadioButtonInactif = new javax.swing.JRadioButton();
        jLabelDateCreation = new javax.swing.JLabel();
        jLabelStockAlerte = new javax.swing.JLabel();
        jTextFieldStockAlerte = new javax.swing.JTextField();
        jComboBoxFournisseur = new javax.swing.JComboBox<>();
        jComboBoxTVA = new javax.swing.JComboBox<>();
        jComboBoxfamilleArticle = new javax.swing.JComboBox<>();
        jRadioButtonParMarge = new javax.swing.JRadioButton();
        jRadioButtonParPrixTTC = new javax.swing.JRadioButton();
        jButtonCalculerPrix = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ErreurLabel = new javax.swing.JLabel();

        confirmSupp.setTitle(Données.getNomLogiciel() + " | confirmation de suppression");
        confirmSupp.setAlwaysOnTop(true);
        confirmSupp.setMinimumSize(new java.awt.Dimension(400, 219));
        confirmSupp.setResizable(false);
        confirmSupp.setSize(new java.awt.Dimension(400, 176));

        jPanel4.setMinimumSize(new java.awt.Dimension(400, 219));

        jButtonCSNon.setText("NON");
        jButtonCSNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSNonActionPerformed(evt);
            }
        });

        jButtonCSOui.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCSOui.setText("OUI");
        jButtonCSOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSOuiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Etes vous sûr de vouloir supprimer cette fiche Article ?");

        jPanel7.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(Données.getNomLogiciel() + " | Connexion ");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonCSOui, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonCSNon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCSNon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCSOui, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout confirmSuppLayout = new javax.swing.GroupLayout(confirmSupp.getContentPane());
        confirmSupp.getContentPane().setLayout(confirmSuppLayout);
        confirmSuppLayout.setHorizontalGroup(
            confirmSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        confirmSuppLayout.setVerticalGroup(
            confirmSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        erreurSupprArticle.setTitle(Données.getNomLogiciel() + " | Erreur de suppression");
        erreurSupprArticle.setAlwaysOnTop(true);
        erreurSupprArticle.setIconImage(null);
        erreurSupprArticle.setMinimumSize(new java.awt.Dimension(400, 234));
        erreurSupprArticle.setResizable(false);
        erreurSupprArticle.setSize(new java.awt.Dimension(400, 176));

        jPanel5.setMinimumSize(new java.awt.Dimension(400, 234));

        jButtonErreurFermer.setText("Fermer");
        jButtonErreurFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonErreurFermerActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("du mouvement de stock !");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Erreur : La suppression est impossible car il y a ");

        jPanel6.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel1.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel1.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NomLogiciel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButtonErreurFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jButtonErreurFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout erreurSupprArticleLayout = new javax.swing.GroupLayout(erreurSupprArticle.getContentPane());
        erreurSupprArticle.getContentPane().setLayout(erreurSupprArticleLayout);
        erreurSupprArticleLayout.setHorizontalGroup(
            erreurSupprArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        erreurSupprArticleLayout.setVerticalGroup(
            erreurSupprArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Données.getNomLogiciel() + " | Ficher Articles ");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        UserListCellRenderer cellRenderer = new UserListCellRenderer();
        jTable1.setDefaultRenderer(Object.class, cellRenderer);
        jTable1.setDefaultRenderer(Double.class, cellRenderer);
        jTable1.setDefaultRenderer(Integer.class, cellRenderer);
        jTable1.setDefaultRenderer(Float.class, cellRenderer);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            Article,
            nomCloArticle) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(51, 153, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(130, 244, 15));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(6).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(6).setMinWidth(0);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(70);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(180);
        }

        jPanel3.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(NomLogiciel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Fichier Articles");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Article selectionné :");

        jLabelCodeBar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCodeBar.setText("Code Barre ");

        jTextFieldCodeBar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldCodeBar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCodeBar.setEnabled(false);

        jLabelDesignation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDesignation.setText("Désignation");

        jTextFieldDesignation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldDesignation.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDesignation.setEnabled(false);

        jLabelStock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelStock.setText("Stock");

        jTextFieldStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldStock.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldStock.setEnabled(false);

        jLabelDerniereVente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDerniereVente.setText("Derniere vente");

        jTextFieldDernierVente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldDernierVente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDernierVente.setEnabled(false);

        jLabelDernierModif.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDernierModif.setText("Dernière modif");

        jTextFieldDerniereModif.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldDerniereModif.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDerniereModif.setEnabled(false);

        jLabelPrixAchat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrixAchat.setText("Prix d'achat HT");

        jTextFieldPrixArchat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPrixArchat.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPrixArchat.setEnabled(false);

        jLabelMarge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMarge.setText("Marge  ");

        jTextFieldMarge.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldMarge.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMarge.setEnabled(false);

        jLabelTVA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTVA.setText("TVA");

        jLabelPrixDeVente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrixDeVente.setText("Prix de vente TTC");

        jTextFieldPrixDeVente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPrixDeVente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPrixDeVente.setEnabled(false);

        jLabelFournisseur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFournisseur.setText("Fournisseur");

        jLabelFamilleArticle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFamilleArticle.setText("Famille Article");

        jTextFieldDateCreation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldDateCreation.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDateCreation.setEnabled(false);

        jButtonSuprimer.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSuprimer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonSuprimer.setText("Supprimer *");
        jButtonSuprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuprimerActionPerformed(evt);
            }
        });

        jButtonCreer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonCreer.setText("Créer article");
        jButtonCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerActionPerformed(evt);
            }
        });

        jButtonModifier.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        buttonGroupActifInactif.add(jRadioButtonActif);
        jRadioButtonActif.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButtonActif.setText("Actif");
        jRadioButtonActif.setEnabled(false);

        buttonGroupActifInactif.add(jRadioButtonInactif);
        jRadioButtonInactif.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButtonInactif.setText("Inactif");
        jRadioButtonInactif.setEnabled(false);

        jLabelDateCreation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDateCreation.setText("Date création");

        jLabelStockAlerte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelStockAlerte.setText("Stock Alerte");

        jTextFieldStockAlerte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldStockAlerte.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldStockAlerte.setEnabled(false);

        jComboBoxFournisseur.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxFournisseur.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxFournisseur.setRenderer(new DefaultListCellRenderer() {
            public void paint(Graphics g) {
                setForeground(new java.awt.Color(0, 0, 0));
                super.paint(g);
            }
        });
        jComboBoxFournisseur.setEnabled(false);
        int i =0;
        while (fournisseur[i] != null && i < fournisseur.length){
            jComboBoxFournisseur.addItem(fournisseur[i]);
            i++;
        }

        jComboBoxTVA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxTVA.setRenderer(new DefaultListCellRenderer() {
            public void paint(Graphics g) {
                setForeground(new java.awt.Color(0, 0, 0));
                super.paint(g);
            }
        });
        jComboBoxTVA.setEnabled(false);
        int ia =0;
        while (TVA[ia] != null && ia < TVA.length){
            jComboBoxTVA.addItem(TVA[ia]);
            ia++;
        }

        jComboBoxfamilleArticle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxfamilleArticle.setRenderer(new DefaultListCellRenderer() {
            public void paint(Graphics g) {
                setForeground(new java.awt.Color(0, 0, 0));
                super.paint(g);
            }
        });
        jComboBoxfamilleArticle.setEnabled(false);
        int ib = 0;
        while (familleArticle[ib] != null && ib < familleArticle.length){
            jComboBoxfamilleArticle.addItem(familleArticle[ib]);
            ib++;
        }

        buttonGroupCalculPrix.add(jRadioButtonParMarge);
        jRadioButtonParMarge.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButtonParMarge.setText("Par marge");
        jRadioButtonParMarge.setEnabled(false);
        jRadioButtonParMarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonParMargeActionPerformed(evt);
            }
        });

        buttonGroupCalculPrix.add(jRadioButtonParPrixTTC);
        jRadioButtonParPrixTTC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButtonParPrixTTC.setText("Par prix TTC");
        jRadioButtonParPrixTTC.setEnabled(false);
        jRadioButtonParPrixTTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonParPrixTTCActionPerformed(evt);
            }
        });

        jButtonCalculerPrix.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonCalculerPrix.setText("Calculer");
        jButtonCalculerPrix.setEnabled(false);
        jButtonCalculerPrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculerPrixActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Historique Achats");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonModifier)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreer)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSuprimer)
                        .addGap(326, 326, 326)
                        .addComponent(jRadioButtonActif, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonInactif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelFamilleArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxfamilleArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCodeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCodeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelPrixAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldPrixArchat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelMarge, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jComboBoxTVA, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabelTVA, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(26, 26, 26)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelPrixDeVente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldPrixDeVente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jRadioButtonParMarge)
                                                    .addComponent(jTextFieldMarge, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButtonParPrixTTC)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonCalculerPrix))))
                                    .addComponent(jLabelDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(163, 163, 163)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelStock, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelStockAlerte, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldStockAlerte, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(219, 219, 219)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDernierModif, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDerniereModif, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDerniereVente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDernierVente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDateCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDateCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelDerniereVente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldDernierVente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelDateCreation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldDateCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelDernierModif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDerniereModif, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCodeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDesignation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCodeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelStock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldMarge, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextFieldPrixArchat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldPrixDeVente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBoxTVA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonCalculerPrix)
                                        .addGap(3, 3, 3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelPrixAchat)
                                            .addComponent(jLabelMarge)
                                            .addComponent(jLabelTVA)
                                            .addComponent(jLabelPrixDeVente))
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabelFournisseur)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jComboBoxFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRadioButtonParMarge)
                                            .addComponent(jRadioButtonParPrixTTC))))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonModifier)
                                    .addComponent(jButtonCreer)
                                    .addComponent(jRadioButtonInactif)
                                    .addComponent(jRadioButtonActif)
                                    .addComponent(jButtonSuprimer)
                                    .addComponent(jButton2)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelStockAlerte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldStockAlerte, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelFamilleArticle)
                                        .addGap(37, 37, 37))
                                    .addComponent(jComboBoxfamilleArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)))))
                .addContainerGap())
        );

        jRadioButtonActif.getAccessibleContext().setAccessibleDescription("");
        jComboBoxFournisseur.setSelectedIndex(-1);
        jComboBoxTVA.setSelectedIndex(-1);
        jComboBoxfamilleArticle.setSelectedIndex(-1);

        ErreurLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ErreurLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1810, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1886, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        ErreurLabel.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        if (statutModif == false && statutCréa == false && idArticleSelect != 0){
            idLigneAModif = idLigneSelect;
            idArticleAModif = idArticleSelect;
            statutModif = true;
            jButtonModifier.setText("Valider");
            jButtonModifier.setBackground(new java.awt.Color(53, 219, 73));
            
            jTextFieldCodeBar.setEnabled(true);
            jTextFieldDesignation.setEnabled(true);
            jTextFieldPrixArchat.setEnabled(true);
            jTextFieldPrixDeVente.setEnabled(true);
            jTextFieldMarge.setEnabled(true);
            jTextFieldStockAlerte.setEnabled(true);
            jComboBoxfamilleArticle.setEnabled(true);
            jComboBoxFournisseur.setEnabled(true);
            jComboBoxTVA.setEnabled(true);
            jRadioButtonActif.setEnabled(true);
            jRadioButtonInactif.setEnabled(true);
            jRadioButtonParMarge.setEnabled(true);
            jRadioButtonParPrixTTC.setEnabled(true);
            buttonGroupCalculPrix.clearSelection();
            jButtonCalculerPrix.setEnabled(true);
            
            System.out.println("Ouvert a la modif");
            
        }else if (statutModif == true && statutCréa == false){
            try {
                statutModif = false;
                System.out.println("valider");
                LocalDate localDate = LocalDate.now();
                
                String sql = "UPDATE Article SET A_Statut = ?, A_EAN=?, A_Designation=?, A_PrixAchat = ?, A_Marge = ?, A_StockAlerte = ?, A_PrixDeVente = ?, A_DateModif =?, Fournisseur_idFournisseur = ?, TVA_idTVA =?, FamilleArticle_idFamilleArticle = ? WHERE idArticle = ?";
                PreparedStatement mdofiArticle = conn.prepareStatement(sql);
                
                if(jRadioButtonActif.isSelected()){
                    mdofiArticle.setInt(1, 1);
                    Article[idLigneAModif][0] =1;
                    jTable1.setValueAt(1, idLigneAModif, 0);
                }else{
                    mdofiArticle.setInt(1, 0);
                    Article[idLigneAModif][0] = 0;
                    jTable1.setValueAt(0, idLigneAModif, 0);
                }
                mdofiArticle.setString(2, jTextFieldCodeBar.getText());
                mdofiArticle.setString(3, jTextFieldDesignation.getText());
                mdofiArticle.setFloat(4, Float.parseFloat(jTextFieldPrixArchat.getText()));
                mdofiArticle.setFloat(5, Float.parseFloat(jTextFieldMarge.getText()));
                mdofiArticle.setInt(6, Integer.parseInt(jTextFieldStockAlerte.getText()));
                mdofiArticle.setFloat(7, Float.parseFloat(jTextFieldPrixDeVente.getText()));
                mdofiArticle.setString(8, localDate.toString());
                mdofiArticle.setInt(9, recupIdFournisseur(jComboBoxFournisseur.getSelectedItem().toString()));
                mdofiArticle.setInt(10, recupIdTVA(jComboBoxTVA.getSelectedItem().toString()));
                mdofiArticle.setInt(11, recupIdFamilleArticle(jComboBoxfamilleArticle.getSelectedItem().toString()));
                mdofiArticle.setInt(12, idArticleAModif);
                mdofiArticle.execute();
                mdofiArticle.close();
                
                jTextFieldDerniereModif.setText(localDate.toString());
                jButtonModifier.setText("Modfier");
                jButtonModifier.setBackground(new java.awt.Color(210, 210, 210));
                jTextFieldCodeBar.setEnabled(false);
                jTextFieldDesignation.setEnabled(false);
                jTextFieldPrixArchat.setEnabled(false);
                jTextFieldPrixDeVente.setEnabled(false);
                jTextFieldMarge.setEnabled(false);
                jTextFieldStockAlerte.setEnabled(false);
                jComboBoxfamilleArticle.setEnabled(false);
                jComboBoxFournisseur.setEnabled(false);
                jComboBoxTVA.setEnabled(false);
                jRadioButtonInactif.setEnabled(false);
                jRadioButtonActif.setEnabled(false);
                jRadioButtonParMarge.setEnabled(false);
                jRadioButtonParPrixTTC.setEnabled(false);
                buttonGroupCalculPrix.clearSelection();
                jButtonCalculerPrix.setEnabled(false);

                Article[idLigneAModif][1] = jTextFieldCodeBar.getText();
                jTable1.setValueAt(jTextFieldCodeBar.getText(), idLigneAModif, 1);
                Article[idLigneAModif][2] = jTextFieldDesignation.getText();
                jTable1.setValueAt(jTextFieldDesignation.getText(), idLigneAModif, 2);
                Article[idLigneAModif][3] = Float.parseFloat(jTextFieldPrixDeVente.getText());
                jTable1.setValueAt(Float.parseFloat(jTextFieldPrixDeVente.getText()), idLigneAModif, 3); 
         
            } catch (CommunicationsException e) {
                Bdd.lostCO(e);    
            } catch (SQLException ex) {
                ErreurLabel.setText("Vous devez saisir des valeurs correctes ! Erreur : " + ex.getMessage());
            }
        }else{
            System.out.println("erreur");
        }
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String idArticleSelect_s = jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString(); // 6 pour idArticle
        idArticleSelect = Integer.parseInt(idArticleSelect_s);
//        System.err.println(idArticleSelect);
         idLigneSelect = jTable1.getSelectedRow();
        
        
        try {
            if (statutModif == false && statutCréa == false && ErreurCréa == false){
                String sql = "SELECT A_EAN, A_Statut, A_Designation, A_PrixAchat, A_Marge, A_PrixDeVente, A_Stock, A_StockAlerte, A_DateCréa, A_DateModif, A_DerniereVente, FamilleArticle.FA_Nom, Fournisseur.F_Nom, TVA.TVA_Taux\n" +
                            "FROM `Article` \n" +
                            "INNER JOIN FamilleArticle on  Article.FamilleArticle_idFamilleArticle = FamilleArticle.idFamilleArticle\n" +
                            "INNER JOIN Fournisseur on Article.Fournisseur_idFournisseur = Fournisseur.idFournisseur\n" +
                            "INNER JOIN TVA on Article.TVA_idTVA = TVA.idTVA\n" +
                            "WHERE idArticle = ?";
                PreparedStatement RecupInfoArticle = conn.prepareStatement(sql);

                RecupInfoArticle.setInt(1, idArticleSelect);
                ResultSet result = RecupInfoArticle.executeQuery();

                while(result.next()){
                    A_statut = result.getInt("A_Statut");
                    A_EAN = result.getString("A_EAN");
                    A_Designation = result.getString("A_Designation");
                    A_PrixAchat = result.getString("A_PrixAchat");
                    A_Marge = result.getString("A_Marge");
                    A_PrixDeVente = result.getString("A_PrixDeVente");
                    A_Stock = result.getString("A_Stock");
                    A_StockAlerte = result.getString("A_StockAlerte");
                    A_DateCréa = result.getString("A_DateCréa");
                    A_DateModif = result.getString("A_DateModif");
                    A_DerniereVente = result.getString("A_DerniereVente");
                    FA_Nom = result.getString("FamilleArticle.FA_Nom");
                    F_Nom = result.getString("Fournisseur.F_Nom");
                    TVA_Taux = result.getString("TVA.TVA_Taux");
                }

                result.close();
                RecupInfoArticle.close();
                jTextFieldCodeBar.setText(A_EAN);
                jTextFieldCodeBar.setEnabled(false);
                jTextFieldDesignation.setText(A_Designation);
                jTextFieldDesignation.setEnabled(false);
                jTextFieldPrixArchat.setText(A_PrixAchat);
                jTextFieldPrixArchat.setEnabled(false);
                jTextFieldPrixDeVente.setText(A_PrixDeVente);
                jTextFieldPrixDeVente.setEnabled(false);
                jTextFieldMarge.setText(A_Marge);
                jTextFieldMarge.setEnabled(false);
                jTextFieldStock.setText(A_Stock);
                jTextFieldStock.setEnabled(false);
                jTextFieldStockAlerte.setText(A_StockAlerte);
                jTextFieldStockAlerte.setEnabled(false);
                jTextFieldDateCreation.setText(A_DateCréa);
                jTextFieldDateCreation.setEnabled(false);
                jTextFieldDernierVente.setText(A_DerniereVente);
                jTextFieldDernierVente.setEnabled(false);
                jTextFieldDerniereModif.setText(A_DateModif);
                jTextFieldDerniereModif.setEnabled(false);
                jComboBoxfamilleArticle.setSelectedItem(FA_Nom);
                jComboBoxfamilleArticle.setEnabled(false);
                jComboBoxFournisseur.setSelectedItem(F_Nom);
                jComboBoxFournisseur.setEnabled(false);
                jComboBoxTVA.setSelectedItem(TVA_Taux);
                jComboBoxTVA.setEnabled(false);
                jRadioButtonActif.setEnabled(false);
                jRadioButtonInactif.setEnabled(false);
                jRadioButtonParMarge.setEnabled(false);
                jRadioButtonParPrixTTC.setEnabled(false);
                buttonGroupCalculPrix.clearSelection();
                jButtonCalculerPrix.setEnabled(false);
                if(A_statut == 1){
                    jRadioButtonActif.setSelected(true);
                }else{
                    jRadioButtonInactif.setSelected(true);
                }
                
            }
            
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(FichierArticle.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonSuprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuprimerActionPerformed
        if(statutCréa == false && statutModif == false && idArticleSelect != 0){
            confirmSupp.setVisible(true);
        }
    }//GEN-LAST:event_jButtonSuprimerActionPerformed

    private void jButtonCSOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSOuiActionPerformed
        if (statutCréa == false && statutModif == false && idArticleSelect != 0){

            String DateDernierVente="0";
            String DateDernierES="0";
            int idArticleSelect_copie = idArticleSelect;
            int idLigneSelect_copie = idLigneSelect;
            try {
                String sql = "SELECT A_DerniereVente, A_DerniereES FROM Article WHERE idArticle = ?";
                PreparedStatement verifDerniereVente = conn.prepareStatement(sql);
                verifDerniereVente.setInt(1, idArticleSelect_copie);
                
                ResultSet result = verifDerniereVente.executeQuery();
            
                while(result.next()){
                    DateDernierVente = result.getString("A_DerniereVente");
                    DateDernierES = result.getString("A_DerniereES");
                }
                
                verifDerniereVente.execute();
                verifDerniereVente.close();
                
            } catch (CommunicationsException e) {
                Bdd.lostCO(e);
            } catch (SQLException ex) {
                Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(DateDernierVente == null && DateDernierES == null){
                
                try {
                    String sql = "DELETE FROM Article WHERE idArticle = ?";
                    PreparedStatement suppArticle = conn.prepareStatement(sql);
                    suppArticle.setInt(1, idArticleSelect_copie);
                
                    suppArticle.execute();
                    suppArticle.close();
                    confirmSupp.setVisible(false);
                    
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.removeRow(idLigneSelect_copie);
                    // ATTENTION il faut supriler l'article dans le tableau  
                    
                } catch (CommunicationsException e) {
                    Bdd.lostCO(e);
                } catch (SQLException ex) {
                    Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                confirmSupp.setVisible(false);
                erreurSupprArticle.setVisible(true);
                //je ne supprime pas l'article car mvt de stock
            }
            
        }
    }//GEN-LAST:event_jButtonCSOuiActionPerformed

    private void jButtonCSNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSNonActionPerformed
        confirmSupp.setVisible(false);
    }//GEN-LAST:event_jButtonCSNonActionPerformed

    private void jButtonCreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerActionPerformed
        if(statutCréa == false && statutModif == false ){
            if(ErreurCréa == false){
                statutCréa = true;
                jButtonCreer.setText("Valider");
                ErreurLabel.setText("");
                jButtonCreer.setBackground(new java.awt.Color(53, 219, 73));
                idArticleSelect = 0;
                jTextFieldCodeBar.setEnabled(true);
                jTextFieldCodeBar.setText("");
                jTextFieldDesignation.setEnabled(true);
                jTextFieldDesignation.setText("");
                jTextFieldPrixArchat.setEnabled(true);
                jTextFieldPrixArchat.setText("");
                jTextFieldPrixDeVente.setEnabled(true);
                jTextFieldPrixDeVente.setText("");
                jTextFieldMarge.setEnabled(true);
                jTextFieldMarge.setText("");
                jTextFieldStockAlerte.setEnabled(true);
                jTextFieldStockAlerte.setText("");
                jComboBoxfamilleArticle.setEnabled(true);
                jComboBoxfamilleArticle.setSelectedIndex(-1);
                jComboBoxFournisseur.setEnabled(true);
                jComboBoxFournisseur.setSelectedIndex(-1);
                jComboBoxTVA.setEnabled(true);
                jComboBoxTVA.setSelectedIndex(-1);
                jTextFieldStock.setEnabled(false);
                jTextFieldStock.setText("");
                
                jTextFieldDateCreation.setText("");
                jTextFieldDateCreation.setEnabled(false);
                jTextFieldDerniereModif.setText("");
                jTextFieldDerniereModif.setEnabled(false);
                jTextFieldDateCreation.setText("");
                jTextFieldDernierVente.setText("");
                jTextFieldDernierVente.setEnabled(false);
                jRadioButtonActif.setEnabled(true);
                jRadioButtonActif.setSelected(true);
                jRadioButtonInactif.setEnabled(true);
                jRadioButtonParMarge.setEnabled(true);
                jRadioButtonParPrixTTC.setEnabled(true);
                buttonGroupCalculPrix.clearSelection();
                jButtonCalculerPrix.setEnabled(true);
                
                
                
            }else{
                ErreurCréa =false;
                statutCréa = true;
                jButtonCreer.setText("Valider");
                ErreurLabel.setText("");
                jButtonCreer.setBackground(new java.awt.Color(53, 219, 73));
                idArticleSelect = 0;
            }
            
            
            
        }else if (statutCréa == true && statutModif == false && idArticleSelect == 0){

            statutCréa = false;
            jButtonCreer.setText("Créer article");
            jButtonCreer.setBackground(new java.awt.Color(210, 210, 210));
            ErreurLabel.setText("");
            
            LocalDate localDate = LocalDate.now();
            try {  
                String sql = "INSERT INTO Article(A_Statut, A_EAN, A_Designation, A_PrixAchat, A_Marge, A_Stock, A_StockAlerte, A_PrixDeVente, A_DateCréa, Fournisseur_idFournisseur, TVA_idTVA, FamilleArticle_idFamilleArticle) values (?,?,?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement creerArticle = conn.prepareStatement(sql);
                int statActifInactif;
                if(jRadioButtonActif.isSelected()){
                    creerArticle.setInt(1, 1);
                    statActifInactif = 1;
                }else{
                    creerArticle.setInt(1, 0);
                    statActifInactif = 0;
                }
                
                creerArticle.setString(2, jTextFieldCodeBar.getText());
                creerArticle.setString(3, jTextFieldDesignation.getText());
                creerArticle.setFloat(4, Float.parseFloat(jTextFieldPrixArchat.getText()));
                creerArticle.setFloat(5, Float.parseFloat(jTextFieldMarge.getText()));
                creerArticle.setInt(6, 0); // stock a 0 de base
                creerArticle.setInt(7, Integer.parseInt(jTextFieldStockAlerte.getText()));
                creerArticle.setFloat(8, Float.parseFloat(jTextFieldPrixDeVente.getText()));
                creerArticle.setString(9, localDate.toString());
                creerArticle.setInt(10, recupIdFournisseur(jComboBoxFournisseur.getSelectedItem().toString()));
                creerArticle.setInt(11, recupIdTVA(jComboBoxTVA.getSelectedItem().toString()));
                creerArticle.setInt(12, recupIdFamilleArticle(jComboBoxfamilleArticle.getSelectedItem().toString()));
                
                creerArticle.execute();
                creerArticle.close();
                ErreurLabel.setText("");
                
                
                 jTextFieldCodeBar.setEnabled(false);
                jTextFieldDesignation.setEnabled(false);
                jTextFieldPrixArchat.setEnabled(false);
                jTextFieldPrixDeVente.setEnabled(false);
                jTextFieldMarge.setEnabled(false);
                jTextFieldStockAlerte.setEnabled(false);
                jComboBoxfamilleArticle.setEnabled(false);
                jComboBoxFournisseur.setEnabled(false);
                jComboBoxTVA.setEnabled(false);
                jRadioButtonInactif.setEnabled(false);
                jRadioButtonActif.setEnabled(false);
                jRadioButtonParMarge.setEnabled(false);
                jRadioButtonParPrixTTC.setEnabled(false);
                buttonGroupCalculPrix.clearSelection();
                jButtonCalculerPrix.setEnabled(false);
                
                //ajout dans la table courante
                int nbLigne = jTable1.getRowCount();
                Article = new Object[countArticle()][NbColoneTArticle];
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(new Object[]{statActifInactif, jTextFieldCodeBar.getText(), jTextFieldDesignation.getText(), Float.parseFloat(jTextFieldPrixDeVente.getText()), 0, "", lastIdArticle()});

                
            } catch (CommunicationsException e) {
                Bdd.lostCO(e);
            } catch (SQLException ex) {
                ErreurLabel.setText("Vous devez saisir des valeurs correctes ! Erreur : " + ex.getMessage());
            }catch (NumberFormatException e){
                ErreurLabel.setText("Vous devez saisir des valeurs correctes ! Erreur : " + e.getMessage());
                ErreurCréa = true;
                jButtonCreer.setText("Corriger");
                jButtonCreer.setBackground(new java.awt.Color(249, 194, 78));
            }
        }
    }//GEN-LAST:event_jButtonCreerActionPerformed

    private void jButtonCalculerPrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculerPrixActionPerformed
        if (statutCréa == true || statutModif == true ){
            calculPrix();
        }
    }//GEN-LAST:event_jButtonCalculerPrixActionPerformed

    private void jRadioButtonParMargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonParMargeActionPerformed
        if (statutCréa == true || statutModif == true ){
            jTextFieldPrixDeVente.setEnabled(false);
            jTextFieldPrixDeVente.setText("");
            jTextFieldPrixArchat.setEnabled(true);
            jTextFieldMarge.setEnabled(true);  
        }
        
    }//GEN-LAST:event_jRadioButtonParMargeActionPerformed

    private void jRadioButtonParPrixTTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonParPrixTTCActionPerformed
        if (statutCréa == true || statutModif == true ){
            jTextFieldPrixDeVente.setEnabled(true);
            jTextFieldPrixArchat.setEnabled(true);
            jTextFieldMarge.setEnabled(false);
            jTextFieldMarge.setText("");
        }
    }//GEN-LAST:event_jRadioButtonParPrixTTCActionPerformed

    private void jButtonErreurFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonErreurFermerActionPerformed
        erreurSupprArticle.setVisible(false);
    }//GEN-LAST:event_jButtonErreurFermerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if(Données.getDUA_FichierArticle() == 1){
           
            recupArticle();
            recupFournisseur();
            recupTVA();
            recupFamilleArticle();
            ErreurCréa = false;
            statutCréa = false;
            statutModif = false;
            
            
            try {
                UIManager.setLookAndFeel( new FlatLightLaf() );
            } catch( Exception ex ) {
                System.err.println( "Failed to initialize LaF" );
            }

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FichierArticle().setVisible(true);
                }
            });
            
        }else{
            ViolationDroit.main(null);
        }
    }
    
    private static int countArticle(){ 
        int i = 0;
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT COUNT(*) FROM Article");
            
            while(result.next()){
                i = result.getInt("COUNT(*)");
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return i;
    }
    
    private static int countFournisseur(){ 
        int i = 0;
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT COUNT(*) FROM Fournisseur");
            
            while(result.next()){
                i = result.getInt("COUNT(*)");
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return i+1;
    }
    
    private static int countTVA(){ 
        int i = 0;
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT COUNT(*) FROM TVA");
            
            while(result.next()){
                i = result.getInt("COUNT(*)");
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return i+1;
    }
    
    private static int countFamilleArticle(){ 
        int i = 0;
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT COUNT(*) FROM FamilleArticle");
            
            while(result.next()){
                i = result.getInt("COUNT(*)");
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return i+1;
    }
    
    private static void recupArticle(){
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT A_statut, A_EAN, A_Designation, A_PrixDeVente, A_Stock, A_DerniereVente, idArticle FROM Article ORDER BY `A_EAN` ASC");
            
            int i = 0;
            while(result.next()){
                int j=0;
                Article[i][j++] = result.getInt("A_statut");
                Article[i][j++] = result.getString("A_EAN");
                Article[i][j++] = result.getString("A_Designation");
                Article[i][j++] = result.getFloat("A_PrixDeVente");
                Article[i][j++] = result.getInt("A_Stock");
                Article[i][j++] = result.getDate("A_DerniereVente");
                Article[i][j++] = result.getInt("idArticle");
                i++;
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public static void recupFournisseur(){
        try {
            Statement state = conn.createStatement();
            ResultSet recupFournisseur = state.executeQuery("SELECT F_Nom FROM Fournisseur");
            
            int i = 0;
            while(recupFournisseur.next()){
                fournisseur[i] = recupFournisseur.getString("F_Nom");
                i++;
            }
            recupFournisseur.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static int recupIdFournisseur(String nomFour){
        try {
            String sql = "SELECT idFournisseur FROM Fournisseur WHERE F_Nom = ?";
                PreparedStatement creerArticle = conn.prepareStatement(sql);
                creerArticle.setString(1, nomFour);
                ResultSet result = creerArticle.executeQuery();
            
                while(result.next()){
                    int id = result.getInt("idFournisseur");
                    return id;
                }
                
                creerArticle.execute();
                creerArticle.close();
                
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }
    
    public static void recupTVA(){
        try {
            Statement stateTVA = conn.createStatement();
            ResultSet recupTVA = stateTVA.executeQuery("SELECT TVA_Taux FROM TVA");
            
            int i = 0;
            while(recupTVA.next()){
                TVA[i] = recupTVA.getString("TVA_Taux");
                i++;
            }
            recupTVA.close();
            stateTVA.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static int recupIdTVA(String TauxTVA){
        try {
            String sql = "SELECT idTVA FROM TVA WHERE TVA_Taux = ?";
                PreparedStatement creerArticle = conn.prepareStatement(sql);
                creerArticle.setFloat(1, Float.parseFloat(TauxTVA));
                ResultSet result = creerArticle.executeQuery();
            
                while(result.next()){
                    int id = result.getInt("idTVA");
                    return id;
                }
                
                creerArticle.execute();
                creerArticle.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);        
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }
    
    public static void recupFamilleArticle(){
        try {
            Statement stateFA = conn.createStatement();
            ResultSet recupFamilleArticle = stateFA.executeQuery("SELECT FA_Nom FROM FamilleArticle");
            
            int i = 0;
            while(recupFamilleArticle.next()){
                familleArticle[i] = recupFamilleArticle.getString("FA_Nom");
                i++;
            }
            recupFamilleArticle.close();
            stateFA.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static int recupIdFamilleArticle(String fA){
        try {
            String sql = "SELECT idFamilleArticle FROM FamilleArticle WHERE FA_Nom = ?";
                PreparedStatement creerArticle = conn.prepareStatement(sql);
                creerArticle.setString(1, fA);
                ResultSet result = creerArticle.executeQuery();
            
                while(result.next()){
                    int id = result.getInt("idFamilleArticle");
                    return id;
                }
                
                creerArticle.execute();
                creerArticle.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }
    
    public static int lastIdArticle(){
        int id = 0;
        try {
            Statement stateTVA = conn.createStatement();
            ResultSet lastIdA = stateTVA.executeQuery("SELECT MAX(idArticle) FROM Article");
            
            while(lastIdA.next()){
                id = lastIdA.getInt("MAX(idArticle)");
            }
            lastIdA.close();
            stateTVA.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return id;
    }
    
    public void calculPrix(){
        if(jRadioButtonParMarge.isSelected()){
            float PrixHT = Float.parseFloat(jTextFieldPrixArchat.getText());
            float Marge = Float.parseFloat(jTextFieldMarge.getText());
            float TVA =  Float.parseFloat(jComboBoxTVA.getSelectedItem().toString());
            
            DecimalFormat df = new DecimalFormat("#0.00");
            DecimalFormatSymbols Symbole = new DecimalFormatSymbols();
            Symbole.setDecimalSeparator('.');
            df.setDecimalFormatSymbols(Symbole);
            
            float PrixTTC = PrixHT+((PrixHT+(PrixHT*Marge))*TVA);
            
            
            jTextFieldPrixDeVente.setEnabled(false);
            jTextFieldPrixDeVente.setText(df.format(PrixTTC));
            
            
        }else if (jRadioButtonParPrixTTC.isSelected()){
            float PrixHT = Float.parseFloat(jTextFieldPrixArchat.getText());
            float PrixTTC = Float.parseFloat(jTextFieldPrixDeVente.getText());
            float TVA =  Float.parseFloat(jComboBoxTVA.getSelectedItem().toString());
            
            DecimalFormat df = new DecimalFormat("#0.000");
            DecimalFormatSymbols Symbole = new DecimalFormatSymbols();
            Symbole.setDecimalSeparator('.');
            df.setDecimalFormatSymbols(Symbole);
            
            float Marge = (((PrixTTC - PrixHT) / TVA) - PrixHT) / PrixHT;
            jTextFieldMarge.setEnabled(false);
            jTextFieldMarge.setText(df.format(Marge));
        }
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErreurLabel;
    private javax.swing.JLabel NomLogiciel;
    private javax.swing.JLabel NomLogiciel1;
    private javax.swing.ButtonGroup buttonGroupActifInactif;
    private javax.swing.ButtonGroup buttonGroupCalculPrix;
    private javax.swing.JDialog confirmSupp;
    private javax.swing.JDialog erreurSupprArticle;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCSNon;
    private javax.swing.JButton jButtonCSOui;
    private javax.swing.JButton jButtonCalculerPrix;
    private javax.swing.JButton jButtonCreer;
    private javax.swing.JButton jButtonErreurFermer;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSuprimer;
    private javax.swing.JComboBox<String> jComboBoxFournisseur;
    private javax.swing.JComboBox<String> jComboBoxTVA;
    private javax.swing.JComboBox<String> jComboBoxfamilleArticle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCodeBar;
    private javax.swing.JLabel jLabelDateCreation;
    private javax.swing.JLabel jLabelDernierModif;
    private javax.swing.JLabel jLabelDerniereVente;
    private javax.swing.JLabel jLabelDesignation;
    private javax.swing.JLabel jLabelFamilleArticle;
    private javax.swing.JLabel jLabelFournisseur;
    private javax.swing.JLabel jLabelMarge;
    private javax.swing.JLabel jLabelPrixAchat;
    private javax.swing.JLabel jLabelPrixDeVente;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JLabel jLabelStockAlerte;
    private javax.swing.JLabel jLabelTVA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButtonActif;
    private javax.swing.JRadioButton jRadioButtonInactif;
    private javax.swing.JRadioButton jRadioButtonParMarge;
    private javax.swing.JRadioButton jRadioButtonParPrixTTC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCodeBar;
    private javax.swing.JTextField jTextFieldDateCreation;
    private javax.swing.JTextField jTextFieldDernierVente;
    private javax.swing.JTextField jTextFieldDerniereModif;
    private javax.swing.JTextField jTextFieldDesignation;
    private javax.swing.JTextField jTextFieldMarge;
    private javax.swing.JTextField jTextFieldPrixArchat;
    private javax.swing.JTextField jTextFieldPrixDeVente;
    private javax.swing.JTextField jTextFieldStock;
    private javax.swing.JTextField jTextFieldStockAlerte;
    // End of variables declaration//GEN-END:variables
}
