/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import com.formdev.flatlaf.FlatLightLaf;
import com.mysql.jdbc.exceptions.jdbc4.CommunicationsException;
import extend.UserListCellRenderer;
import java.awt.Graphics;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author etien
 */
public class FichierClient extends javax.swing.JFrame {
    
    private static Connection conn = Bdd.coBdd(); //Instanciation de la variable de connexion à la base de données

    private static int NbColonneTclient = 6;
    private static Object[][] Client = new Object[countClient()][NbColonneTclient];
    private static String [] nomColClient = { "Statut", "Code Client", "Nom", "Prénom", "Date création", "Email"};
      
    
    private static int idClientSelect = 0;
    private static int idLigneSelect;
    private static int idLigneAModif;
    
    private static boolean statutModif = false;
    private static boolean statutCréa = false;
    private static boolean ErreurCréa = false;
    
    private static int C_statut;
    private static String C_CodeClient;
    private static String C_Nom;
    private static String C_Prenom;
    private static String C_DateCrea;
    private static String C_Email;
    private static String C_Adresse;
    private static String C_CodePostale;
    private static String C_Ville;
    private static String C_Tel;
    private static String C_DateModif;
    private static String CarteFid_idCarteFid;
    private static String LastIdFid;
    private static String CF_Points;

    
    /**
     * Creates new form FichierArticle
     */
    public FichierClient() {
        initComponents();
        URL iconURL = getClass().getResource(Données.getUrl_Logo());
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        confirmSupp.setIconImage(icon.getImage());
        confirmSupp.setLocationRelativeTo(this);
        erreurSupprClient.setIconImage(icon.getImage());
        erreurSupprClient.setLocationRelativeTo(this);
        erreurClientComptoir.setLocationRelativeTo(this);
        erreurClientComptoir.setIconImage(icon.getImage());
        GestionFid.setLocationRelativeTo(this);
        GestionFid.setIconImage(icon.getImage());
        
        setExtendedState(JFrame.MAXIMIZED_BOTH); // ouverture de la fenetre en full screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmSupp = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jButtonCSNon = new javax.swing.JButton();
        jButtonCSOui = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        erreurSupprClient = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jButtonErreurFermer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        NomLogiciel1 = new javax.swing.JLabel();
        buttonGroupAcIn = new javax.swing.ButtonGroup();
        erreurClientComptoir = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jButtonErreurFermer1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        NomLogiciel2 = new javax.swing.JLabel();
        GestionFid = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        nouvelleCarteFid = new javax.swing.JButton();
        BoutonValiderCarte = new javax.swing.JButton();
        jTextFieldGnoFid = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        NomLogiciel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldGpts = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        NomLogiciel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelCodeBar = new javax.swing.JLabel();
        jTextFieldAdresse = new javax.swing.JTextField();
        jLabelNom = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabelDernierModif = new javax.swing.JLabel();
        jTextFieldDerniereModif = new javax.swing.JTextField();
        jTextFieldDateCreation = new javax.swing.JTextField();
        jButtonSuprimer = new javax.swing.JButton();
        jButtonCreer = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jLabelDateCreation = new javax.swing.JLabel();
        jTextFieldPrenom = new javax.swing.JTextField();
        jLabelPrénom = new javax.swing.JLabel();
        jTextFieldCodeClient = new javax.swing.JTextField();
        jTextFieldVille = new javax.swing.JTextField();
        jTextFieldCP = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldTel = new javax.swing.JTextField();
        jTextFieldSoldePts = new javax.swing.JTextField();
        jTextFieldNumCarteFid = new javax.swing.JTextField();
        jRadioButtonActif = new javax.swing.JRadioButton();
        jRadioButtonInactif = new javax.swing.JRadioButton();
        jLabelNom1 = new javax.swing.JLabel();
        jLabelNom2 = new javax.swing.JLabel();
        jLabelNom3 = new javax.swing.JLabel();
        jLabelPrénom1 = new javax.swing.JLabel();
        jLabelPrénom2 = new javax.swing.JLabel();
        jLabelDernierModif1 = new javax.swing.JLabel();
        jLabelDernierModif2 = new javax.swing.JLabel();
        jButtonCarteFid = new javax.swing.JButton();
        ErreurLabel = new javax.swing.JLabel();

        confirmSupp.setTitle(Données.getNomLogiciel() + " | confirmation de suppression");
        confirmSupp.setAlwaysOnTop(true);
        confirmSupp.setMinimumSize(new java.awt.Dimension(400, 219));
        confirmSupp.setResizable(false);
        confirmSupp.setSize(new java.awt.Dimension(400, 176));

        jPanel4.setMinimumSize(new java.awt.Dimension(400, 219));

        jButtonCSNon.setText("NON");
        jButtonCSNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSNonActionPerformed(evt);
            }
        });

        jButtonCSOui.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCSOui.setText("OUI");
        jButtonCSOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSOuiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Etes vous sûr de vouloir supprimer cette fiche Client ?");

        jPanel7.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(Données.getNomLogiciel() + " | Connexion ");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonCSOui, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonCSNon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCSNon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCSOui, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout confirmSuppLayout = new javax.swing.GroupLayout(confirmSupp.getContentPane());
        confirmSupp.getContentPane().setLayout(confirmSuppLayout);
        confirmSuppLayout.setHorizontalGroup(
            confirmSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        confirmSuppLayout.setVerticalGroup(
            confirmSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        erreurSupprClient.setTitle(Données.getNomLogiciel() + " | Erreur de suppression");
        erreurSupprClient.setAlwaysOnTop(true);
        erreurSupprClient.setIconImage(null);
        erreurSupprClient.setMinimumSize(new java.awt.Dimension(400, 234));
        erreurSupprClient.setResizable(false);
        erreurSupprClient.setSize(new java.awt.Dimension(400, 176));

        jPanel5.setMinimumSize(new java.awt.Dimension(400, 234));

        jButtonErreurFermer.setText("Fermer");
        jButtonErreurFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonErreurFermerActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("vente a déja été realisée !");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Erreur : La suppression est impossible car une  ");

        jPanel6.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel1.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel1.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NomLogiciel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jButtonErreurFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jButtonErreurFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout erreurSupprClientLayout = new javax.swing.GroupLayout(erreurSupprClient.getContentPane());
        erreurSupprClient.getContentPane().setLayout(erreurSupprClientLayout);
        erreurSupprClientLayout.setHorizontalGroup(
            erreurSupprClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        erreurSupprClientLayout.setVerticalGroup(
            erreurSupprClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        erreurClientComptoir.setTitle(Données.getNomLogiciel() + " | Erreur de suppression");
        erreurClientComptoir.setAlwaysOnTop(true);
        erreurClientComptoir.setIconImage(null);
        erreurClientComptoir.setMinimumSize(new java.awt.Dimension(400, 234));
        erreurClientComptoir.setResizable(false);
        erreurClientComptoir.setSize(new java.awt.Dimension(400, 176));

        jPanel8.setMinimumSize(new java.awt.Dimension(400, 234));

        jButtonErreurFermer1.setText("Fermer");
        jButtonErreurFermer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonErreurFermer1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("\"client comptoir\" !");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Erreur : La suppression/modification est impossible :");

        jPanel9.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel2.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel2.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel2.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NomLogiciel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButtonErreurFermer1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jButtonErreurFermer1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout erreurClientComptoirLayout = new javax.swing.GroupLayout(erreurClientComptoir.getContentPane());
        erreurClientComptoir.getContentPane().setLayout(erreurClientComptoirLayout);
        erreurClientComptoirLayout.setHorizontalGroup(
            erreurClientComptoirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        erreurClientComptoirLayout.setVerticalGroup(
            erreurClientComptoirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        GestionFid.setMinimumSize(new java.awt.Dimension(616, 320));
        GestionFid.setResizable(false);

        jPanel10.setMinimumSize(new java.awt.Dimension(616, 278));

        nouvelleCarteFid.setText("Création fidélité");
        nouvelleCarteFid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouvelleCarteFidActionPerformed(evt);
            }
        });

        BoutonValiderCarte.setBackground(new java.awt.Color(102, 255, 102));
        BoutonValiderCarte.setText("Valider");
        BoutonValiderCarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonValiderCarteActionPerformed(evt);
            }
        });

        jTextFieldGnoFid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldGnoFid.setEnabled(false);

        jPanel11.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel3.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel3.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel3.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NomLogiciel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel3)
                .addContainerGap())
        );

        jLabel9.setText("N° Carte Fidélité");

        jTextFieldGpts.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldGpts.setText("0");

        jLabel10.setText("Points");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nouvelleCarteFid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BoutonValiderCarte)
                .addGap(29, 29, 29))
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldGnoFid)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldGpts)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldGnoFid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldGpts, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonValiderCarte)
                    .addComponent(nouvelleCarteFid))
                .addContainerGap())
        );

        javax.swing.GroupLayout GestionFidLayout = new javax.swing.GroupLayout(GestionFid.getContentPane());
        GestionFid.getContentPane().setLayout(GestionFidLayout);
        GestionFidLayout.setHorizontalGroup(
            GestionFidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        GestionFidLayout.setVerticalGroup(
            GestionFidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Données.getNomLogiciel() + " | Fichier Client ");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        UserListCellRenderer cellRenderer = new UserListCellRenderer();
        jTable1.setDefaultRenderer(Object.class, cellRenderer);
        jTable1.setDefaultRenderer(Double.class, cellRenderer);
        jTable1.setDefaultRenderer(Integer.class, cellRenderer);
        jTable1.setDefaultRenderer(Float.class, cellRenderer);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            Client,
            nomColClient) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            boolean[] canEdit = new boolean [] {
                false,false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(51, 153, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(130, 244, 15));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(70);

        }

        jPanel3.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(NomLogiciel, javax.swing.GroupLayout.PREFERRED_SIZE, 1917, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomLogiciel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Fichier Client");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Client selectionné :");

        jPanel2.setPreferredSize(new java.awt.Dimension(1800, 332));

        jLabelCodeBar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCodeBar.setText("Code Client");

        jTextFieldAdresse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldAdresse.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldAdresse.setEnabled(false);

        jLabelNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNom.setText("Nom");

        jTextFieldNom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNom.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNom.setEnabled(false);

        jLabelDernierModif.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDernierModif.setText("Dernière modif");

        jTextFieldDerniereModif.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldDerniereModif.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDerniereModif.setEnabled(false);

        jTextFieldDateCreation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldDateCreation.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDateCreation.setEnabled(false);

        jButtonSuprimer.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSuprimer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonSuprimer.setText("Supprimer *");
        jButtonSuprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuprimerActionPerformed(evt);
            }
        });

        jButtonCreer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonCreer.setText("Créer client");
        jButtonCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerActionPerformed(evt);
            }
        });

        jButtonModifier.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jLabelDateCreation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDateCreation.setText("Date création");

        jTextFieldPrenom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPrenom.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPrenom.setEnabled(false);

        jLabelPrénom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrénom.setText("Prénom");

        jTextFieldCodeClient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldCodeClient.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCodeClient.setEnabled(false);

        jTextFieldVille.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldVille.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldVille.setEnabled(false);

        jTextFieldCP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldCP.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCP.setEnabled(false);

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldEmail.setEnabled(false);

        jTextFieldTel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldTel.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldTel.setEnabled(false);

        jTextFieldSoldePts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldSoldePts.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldSoldePts.setEnabled(false);

        jTextFieldNumCarteFid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNumCarteFid.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNumCarteFid.setEnabled(false);

        buttonGroupAcIn.add(jRadioButtonActif);
        jRadioButtonActif.setText("Actif");
        jRadioButtonActif.setEnabled(false);

        buttonGroupAcIn.add(jRadioButtonInactif);
        jRadioButtonInactif.setText("Inactif");
        jRadioButtonInactif.setEnabled(false);

        jLabelNom1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNom1.setText("Adresse");

        jLabelNom2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNom2.setText("Ville");

        jLabelNom3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNom3.setText("Code Postal");

        jLabelPrénom1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrénom1.setText("Email");

        jLabelPrénom2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrénom2.setText("Téléphone");

        jLabelDernierModif1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDernierModif1.setText("N° Carte fidélité associée");

        jLabelDernierModif2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDernierModif2.setText("Solde points");

        jButtonCarteFid.setText("Gérer une carte de fidélité");
        jButtonCarteFid.setEnabled(false);
        jButtonCarteFid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarteFidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonInactif)
                            .addComponent(jRadioButtonActif))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNom3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelNom2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(268, 268, 268))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelPrénom1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCodeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCodeClient, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrénom, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonModifier)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreer)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSuprimer)))
                .addGap(120, 120, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNumCarteFid, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDernierModif1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDernierModif2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jTextFieldSoldePts))
                        .addGap(41, 41, 41)
                        .addComponent(jButtonCarteFid, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDateCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDateCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDernierModif, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDerniereModif, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(713, 713, 713)
                    .addComponent(jLabelPrénom2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1072, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelPrénom, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCodeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCodeClient, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonActif)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonInactif)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNom2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNom3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelPrénom1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabelDateCreation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDateCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabelDernierModif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDerniereModif, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDernierModif2)
                            .addComponent(jLabelDernierModif1))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonCreer)
                    .addComponent(jButtonSuprimer)
                    .addComponent(jTextFieldNumCarteFid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSoldePts, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCarteFid))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(190, Short.MAX_VALUE)
                    .addComponent(jLabelPrénom2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(120, 120, 120)))
        );

        ErreurLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ErreurLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1886, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(ErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        ErreurLabel.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        
        if (statutModif == false && statutCréa == false && idClientSelect != 0){
            idLigneAModif = idLigneSelect;
            statutModif = true;
            jButtonModifier.setText("Valider");
            jButtonModifier.setBackground(new java.awt.Color(53, 219, 73));
            
            jTextFieldNom.setEnabled(true);
            jTextFieldPrenom.setEnabled(true);
            jTextFieldAdresse.setEnabled(true);
            jTextFieldCP.setEnabled(true);
            jTextFieldEmail.setEnabled(true);
            jTextFieldVille.setEnabled(true);
            jTextFieldTel.setEnabled(true);
            jRadioButtonActif.setEnabled(true);
            jRadioButtonInactif.setEnabled(true);
            jButtonCarteFid.setEnabled(true);
            
            if (IdClientComptoir() == idClientSelect){
                System.out.println("Err client comptoire");
                statutModif = false;
                jTextFieldNom.setEnabled(false);
                jTextFieldPrenom.setEnabled(false);
                jTextFieldAdresse.setEnabled(false);
                jTextFieldCP.setEnabled(false);
                jTextFieldEmail.setEnabled(false);
                jTextFieldVille.setEnabled(false);
                jTextFieldTel.setEnabled(false);
                jRadioButtonActif.setEnabled(false);
                jRadioButtonInactif.setEnabled(false);
                jButtonCarteFid.setEnabled(false);
                jButtonModifier.setText("Modfier");
                jButtonModifier.setBackground(new java.awt.Color(210, 210, 210));
                erreurClientComptoir.setVisible(true);
            }else{
                System.out.println("Ouvert a la modif");
            }
            
        }else if (statutModif == true && statutCréa == false){
            try {
                statutModif = false;
                System.out.println("valider");
                LocalDate localDate = LocalDate.now();
                 String sql;
                if (!jTextFieldNumCarteFid.getText().equals("")){ // si creation avec creation cart fid 
                    sql = "UPDATE Client SET C_Nom = UPPER(?), C_Prenom = ?, C_Email=?, C_Adresse = ?, C_CodePostale = ?, C_Ville = ?, C_Tel = ?, C_Statut = ?, C_DateModif = ?, CarteFid_idCarteFid = ? WHERE idClient = ?";
                }else {
                    sql = "UPDATE Client SET C_Nom = UPPER(?), C_Prenom = ?, C_Email=?, C_Adresse = ?, C_CodePostale = ?, C_Ville = ?, C_Tel = ?, C_Statut = ?, C_DateModif = ? WHERE idClient = ?";
                }
                
                PreparedStatement mdofiClient = conn.prepareStatement(sql);


                mdofiClient.setString(1, jTextFieldNom.getText());
                mdofiClient.setString(2, jTextFieldPrenom.getText());
                mdofiClient.setString(3, jTextFieldEmail.getText());
                mdofiClient.setString(4, jTextFieldAdresse.getText());
                mdofiClient.setString(5, jTextFieldCP.getText());
                mdofiClient.setString(6, jTextFieldVille.getText());
                mdofiClient.setString(7, jTextFieldTel.getText());

                if(jRadioButtonActif.isSelected()){
                    mdofiClient.setInt(8, 1);
                    Client[idLigneAModif][0] = 1;
                    jTable1.setValueAt(1, idLigneAModif, 0);
                }else{
                    mdofiClient.setInt(8, 0);
                    Client[idLigneAModif][0] = 0;
                    jTable1.setValueAt(0, idLigneAModif, 0);
                }

                mdofiClient.setString(9, localDate.toString());
                
                if (!jTextFieldNumCarteFid.getText().equals("")){ // si creation avec creation cart fid 
                    mdofiClient.setString(10, jTextFieldNumCarteFid.getText());
                    mdofiClient.setInt(11, idClientSelect);
                } else{
                    mdofiClient.setInt(10, idClientSelect);
                }
                
                mdofiClient.execute();
                mdofiClient.close();

                jTextFieldDerniereModif.setText(localDate.toString());
                jButtonModifier.setText("Modfier");
                jButtonModifier.setBackground(new java.awt.Color(210, 210, 210));
                
                jTextFieldNom.setEnabled(false);
                jTextFieldPrenom.setEnabled(false);
                jTextFieldAdresse.setEnabled(false);
                jTextFieldCP.setEnabled(false);
                jTextFieldEmail.setEnabled(false);
                jTextFieldVille.setEnabled(false);
                jTextFieldTel.setEnabled(false);
                jRadioButtonActif.setEnabled(false);
                jRadioButtonInactif.setEnabled(false);
                jButtonCarteFid.setEnabled(false);

                Client[idLigneAModif][2] = jTextFieldNom.getText();
                jTable1.setValueAt(jTextFieldNom.getText(), idLigneAModif, 2);
                Client[idLigneAModif][3] = jTextFieldPrenom.getText();
                jTable1.setValueAt(jTextFieldPrenom.getText(), idLigneAModif, 3);
                Client[idLigneAModif][5] = jTextFieldPrenom.getText();
                jTable1.setValueAt(jTextFieldEmail.getText(), idLigneAModif, 5);
                //finir la maj du tableau avec les infos quon a rentées

            } catch (CommunicationsException e) {
                Bdd.lostCO(e);    
            } catch (SQLException ex) {
                ErreurLabel.setText("Vous devez saisir des valeurs correctes ! Erreur : " + ex.getMessage());
            }
            
            
        }else{
            System.out.println("erreur");
        }
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String idClientSelect_s = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString(); // 1 pour idClient
        idClientSelect = Integer.parseInt(idClientSelect_s);
        //System.err.println(idClientSelect);
        idLigneSelect = jTable1.getSelectedRow();
        
        
        try {
            if (statutModif == false && statutCréa == false && ErreurCréa == false){
                String sql = "SELECT idClient, C_Nom, C_Statut, C_Prenom, C_DateCrea, C_Email, C_Adresse, C_CodePostale, C_Ville, C_Tel, C_DateModif, CarteFid_idCarteFid, CarteFid.CF_points FROM `Client` \n" +
                             "LEFT JOIN CarteFid on Client.CarteFid_idCarteFid = CarteFid.idCarteFid WHERE idClient = ?";
                PreparedStatement RecupInfoClients = conn.prepareStatement(sql);

                RecupInfoClients.setInt(1, idClientSelect);
                ResultSet result = RecupInfoClients.executeQuery();

                while(result.next()){
                    C_CodeClient = result.getString("idClient");
                    C_statut = result.getInt("C_Statut");
                    C_Nom = result.getString("C_Nom");
                    C_Prenom = result.getString("C_Prenom");
                    C_DateCrea = result.getString("C_DateCrea");
                    C_Email = result.getString("C_Email");
                    C_Adresse = result.getString("C_Adresse");
                    C_CodePostale = result.getString("C_CodePostale");
                    C_Ville = result.getString("C_Ville");
                    C_Tel = result.getString("C_Tel");
                    C_DateModif = result.getString("C_DateModif");
                    CarteFid_idCarteFid = result.getString("CarteFid_idCarteFid");
                    CF_Points = result.getString("CarteFid.CF_points");
                }

                result.close();
                RecupInfoClients.close();
                jTextFieldCodeClient.setText(C_CodeClient);
                jTextFieldCodeClient.setEnabled(false);
                jTextFieldDateCreation.setText(C_DateCrea);
                jTextFieldDateCreation.setEnabled(false);
                jTextFieldDerniereModif.setText(C_DateModif);
                jTextFieldDerniereModif.setEnabled(false);
                jTextFieldAdresse.setText(C_Adresse);
                jTextFieldAdresse.setEnabled(false);
                jTextFieldCP.setText(C_CodePostale);
                jTextFieldCP.setEnabled(false);
                jTextFieldEmail.setText(C_Email);
                jTextFieldEmail.setEnabled(false);
                jTextFieldNom.setText(C_Nom);
                jTextFieldNom.setEnabled(false);
                jTextFieldNumCarteFid.setText(CarteFid_idCarteFid);
                jTextFieldGnoFid.setText(CarteFid_idCarteFid);
                jTextFieldNumCarteFid.setEnabled(false);
                jTextFieldPrenom.setText(C_Prenom);
                jTextFieldPrenom.setEnabled(false);
                jTextFieldSoldePts.setText(CF_Points);
                jTextFieldGpts.setText(CF_Points);
                jTextFieldSoldePts.setEnabled(false);
                jTextFieldTel.setText(C_Tel);
                jTextFieldTel.setEnabled(false);
                jTextFieldVille.setText(C_Ville);
                jTextFieldVille.setEnabled(false);
                if(C_statut == 1){
                    jRadioButtonActif.setSelected(true);
                }else{
                    jRadioButtonInactif.setSelected(true);
                }
                jRadioButtonActif.setEnabled(false);
                jRadioButtonInactif.setEnabled(false);
                jButtonCarteFid.setEnabled(false);
                
                if (CarteFid_idCarteFid != null){
                    nouvelleCarteFid.setEnabled(false);
                } else {
                    nouvelleCarteFid.setEnabled(true);
                }
                
                
            }
            
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(FichierClient.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonSuprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuprimerActionPerformed
        if(statutCréa == false && statutModif == false && idClientSelect != 0){
            confirmSupp.setVisible(true);
        }
    }//GEN-LAST:event_jButtonSuprimerActionPerformed

    private void jButtonCSOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSOuiActionPerformed
        if (statutCréa == false && statutModif == false && idClientSelect != 0){

            String nbDeTicketClient="0";
            
            int idClientSelect_copie = idClientSelect;
            int idLigneSelect_copie = idLigneSelect;
            try {
                String sql = "SELECT count(*) FROM TicketDeCaisse WHERE Client_idClient = ?";
                PreparedStatement verifHistoriqueT = conn.prepareStatement(sql);
                verifHistoriqueT.setInt(1, idClientSelect_copie);
                
                ResultSet result = verifHistoriqueT.executeQuery();
            
                while(result.next()){
                    nbDeTicketClient = result.getString("count(*)");
                }
                
                verifHistoriqueT.execute();
                verifHistoriqueT.close();
                
            } catch (CommunicationsException e) {
                Bdd.lostCO(e);
            } catch (SQLException ex) {
                Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (IdClientComptoir() != idClientSelect){
                if(nbDeTicketClient.equals("0")){
                    try {
                        String sql = "DELETE FROM Client WHERE idClient = ?";
                        PreparedStatement suppClient = conn.prepareStatement(sql);
                        suppClient.setInt(1, idClientSelect_copie);

                        suppClient.execute();
                        suppClient.close();
                        confirmSupp.setVisible(false);

                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        model.removeRow(idLigneSelect_copie);
                        // ATTENTION il faut supriler le client dans le tableau  

                    } catch (CommunicationsException e) {
                        Bdd.lostCO(e);
                    } catch (SQLException ex) {
                        Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    confirmSupp.setVisible(false);
                    erreurSupprClient.setVisible(true);
                    //je ne supprime pas le client car vente réalisée
                }
            }else{
                    confirmSupp.setVisible(false);
                    erreurClientComptoir.setVisible(true);
                    //je ne supprime pas le client car vente réalisée
                }
            
        }
    }//GEN-LAST:event_jButtonCSOuiActionPerformed

    private void jButtonCSNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSNonActionPerformed
        confirmSupp.setVisible(false);
    }//GEN-LAST:event_jButtonCSNonActionPerformed

    private void jButtonCreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerActionPerformed
        if(statutCréa == false && statutModif == false ){
            if(ErreurCréa == false){
                statutCréa = true;
                
                jButtonCreer.setText("Valider");
                ErreurLabel.setText("");
                jButtonCreer.setBackground(new java.awt.Color(53, 219, 73));
                idClientSelect = 0;
                jTextFieldAdresse.setEnabled(true);
                jTextFieldAdresse.setText("");
                jTextFieldNom.setEnabled(true);
                jTextFieldNom.setText("");
                jTextFieldPrenom.setEnabled(true);
                jTextFieldPrenom.setText("");
                jTextFieldVille.setEnabled(true);
                jTextFieldVille.setText("");
                jTextFieldCP.setEnabled(true);
                jTextFieldCP.setText("");
                jButtonCarteFid.setEnabled(true);
                jTextFieldTel.setEnabled(true);
                jTextFieldTel.setText("");
                jTextFieldEmail.setEnabled(true);
                jTextFieldEmail.setText("");
                jRadioButtonActif.setSelected(true);
                jRadioButtonActif.setEnabled(true);
                jRadioButtonInactif.setEnabled(true);
                
                jTextFieldDateCreation.setText("");
                jTextFieldDateCreation.setEnabled(false);
                jTextFieldDerniereModif.setText("");
                jTextFieldDerniereModif.setEnabled(false);
                jTextFieldCodeClient.setText("");
                jTextFieldCodeClient.setEnabled(false);
                jTextFieldNumCarteFid.setText("");
                jTextFieldNumCarteFid.setEnabled(false);
                jTextFieldSoldePts.setText("");
                jTextFieldSoldePts.setEnabled(false);
                
                
                
            }else{
                ErreurCréa =false;
                statutCréa = true;
                jButtonCreer.setText("Valider");
                ErreurLabel.setText("");
                jButtonCreer.setBackground(new java.awt.Color(53, 219, 73));
                idClientSelect = 0;
            }
            
            
            
        }else if (statutCréa == true && statutModif == false && idClientSelect == 0){

            statutCréa = false;
            jButtonCreer.setText("Créer Client");
            jButtonCreer.setBackground(new java.awt.Color(210, 210, 210));
            ErreurLabel.setText("");
            
            LocalDate localDate = LocalDate.now();
            try {
                String sql;
                if (!jTextFieldNumCarteFid.getText().equals("")){
                    sql = "INSERT INTO Client (C_Statut, C_Nom, C_Prenom, C_Adresse, C_CodePostale, C_Ville, C_Email, C_Tel, C_DateCrea, CarteFid_idCarteFid) VALUES (?,UPPER(?),?,?,?,?,?,?,?,?)";
                }else {
                    sql = "INSERT INTO Client (C_Statut, C_Nom, C_Prenom, C_Adresse, C_CodePostale, C_Ville, C_Email, C_Tel, C_DateCrea) VALUES (?,UPPER(?),?,?,?,?,?,?,?)";
                }
                PreparedStatement creerClient = conn.prepareStatement(sql);
                
                 int statActifInactif;
                if(jRadioButtonActif.isSelected()){
                    creerClient.setInt(1, 1);
                    statActifInactif = 1;
                }else{
                    creerClient.setInt(1, 0);
                    statActifInactif = 1;
                }
                                
                creerClient.setString(2, jTextFieldNom.getText());
                creerClient.setString(3, jTextFieldPrenom.getText());
                creerClient.setString(4,jTextFieldAdresse.getText());
                creerClient.setString(5, jTextFieldCP.getText());
                creerClient.setString(6,jTextFieldVille.getText());
                creerClient.setString(7,jTextFieldEmail .getText()); 
                creerClient.setString(8,jTextFieldTel.getText());  
                creerClient.setString(9, localDate.toString());  
                if (!jTextFieldNumCarteFid.getText().equals("")){
                    creerClient.setString(10,jTextFieldNumCarteFid.getText());
                }
                
                creerClient.execute();
                creerClient.close();
                
                int lastIdClient;
                Statement state = conn.createStatement();
                ResultSet result = state.executeQuery("SELECT idClient FROM Client ORDER BY idClient DESC LIMIT 1");
                
                while(result.next()){
                    jTextFieldCodeClient.setText(result.getString("idClient"));
                }
                result.close();
                state.close();
                
                ErreurLabel.setText("");
                
                
                jTextFieldNom.setEnabled(false);
                jTextFieldPrenom.setEnabled(false);
                jTextFieldAdresse.setEnabled(false);
                jTextFieldCP.setEnabled(false);
                jTextFieldEmail.setEnabled(false);
                jTextFieldVille.setEnabled(false);
                jTextFieldTel.setEnabled(false);
                jRadioButtonActif.setEnabled(false);
                jRadioButtonInactif.setEnabled(false);
                jButtonCarteFid.setEnabled(false);
                
                //ajout dans la table courante
                int nbLigne = jTable1.getRowCount();
                Client = new Object[countClient()][NbColonneTclient];
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(new Object[]{statActifInactif,jTextFieldCodeClient.getText(), jTextFieldNom.getText(), jTextFieldPrenom.getText(), localDate.toString(), jTextFieldEmail .getText() });

                
            } catch (CommunicationsException e) {
                Bdd.lostCO(e);
            } catch (SQLException ex) {
                ErreurLabel.setText("Vous devez saisir des valeurs correctes ! Erreur : " + ex.getMessage());
            }catch (NumberFormatException e){
                ErreurLabel.setText("Vous devez saisir des valeurs correctes ! Erreur : " + e.getMessage());
                ErreurCréa = true;
                jButtonCreer.setText("Corriger");
                jButtonCreer.setBackground(new java.awt.Color(249, 194, 78));
            }
        }
    }//GEN-LAST:event_jButtonCreerActionPerformed

    private void jButtonErreurFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonErreurFermerActionPerformed
        erreurSupprClient.setVisible(false);
    }//GEN-LAST:event_jButtonErreurFermerActionPerformed

    private void jButtonErreurFermer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonErreurFermer1ActionPerformed
        erreurClientComptoir.setVisible(false);
    }//GEN-LAST:event_jButtonErreurFermer1ActionPerformed

    private void jButtonCarteFidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarteFidActionPerformed
        GestionFid.setVisible(true);
    }//GEN-LAST:event_jButtonCarteFidActionPerformed

    private void BoutonValiderCarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonValiderCarteActionPerformed
        try {
            String sql = "UPDATE CarteFid SET CF_points= ? WHERE idCarteFid = ?";
            PreparedStatement créationCartFid = conn.prepareStatement(sql);
            créationCartFid.setString(1, jTextFieldGpts.getText());
            créationCartFid.setString(2, jTextFieldGnoFid.getText());
            
            créationCartFid.execute();
            créationCartFid.close();
            jTextFieldSoldePts.setText(jTextFieldGpts.getText());
            GestionFid.setVisible(false);
            
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(FichierClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BoutonValiderCarteActionPerformed

    private void nouvelleCarteFidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouvelleCarteFidActionPerformed
        try {
            String sql = "INSERT INTO CarteFid (CF_points) VALUES (?)";
            PreparedStatement créationCartFid = conn.prepareStatement(sql);
            créationCartFid.setInt(1, 0); // 0 pts fid car creation

            créationCartFid.execute();
            créationCartFid.close();
            
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT idCarteFid FROM `CarteFid`ORDER BY idCarteFid DESC LIMIT 1");
            
            while(result.next()){
                LastIdFid = result.getString("idCarteFid");
            }
            result.close();
            state.close();
            
            jTextFieldGnoFid.setText(LastIdFid.toString());
            jTextFieldGpts.setText("0");
            jTextFieldNumCarteFid.setText(LastIdFid.toString());
            jTextFieldSoldePts.setText("0");
            nouvelleCarteFid.setEnabled(false);
            
            
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nouvelleCarteFidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if(Données.getDUA_FichierClient()== 1){
           
            recupClient();
            ErreurCréa = false;
            statutCréa = false;
            statutModif = false;
            
            
            try {
                UIManager.setLookAndFeel( new FlatLightLaf() );
            } catch( Exception ex ) {
                System.err.println( "Failed to initialize LaF" );
            }

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FichierClient().setVisible(true);
                }
            });
            
        }else{
            ViolationDroit.main(null);
        }
    }
    
    private static int countClient(){ 
        int i = 0;
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT COUNT(*) FROM Client");
            
            while(result.next()){
                i = result.getInt("COUNT(*)");
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return i;
    }
    
    private static void recupClient(){
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT idClient, C_Statut, C_Nom, C_Prenom, C_DateCrea, C_Email FROM Client ORDER BY `C_Nom` ASC");
            
            int i = 0;
            while(result.next()){
                int j=0;
                Client[i][j++] = result.getInt("C_Statut");
                Client[i][j++] = result.getInt("idClient");
                Client[i][j++] = result.getString("C_Nom");
                Client[i][j++] = result.getString("C_Prenom");
                Client[i][j++] = result.getString("C_DateCrea");
                Client[i][j++] = result.getString("C_Email");
                i++;
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private static int IdClientComptoir(){ 
        int idClientCompoire_BDD = 1;
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT C_GidClientcomptoire FROM Conf_G");
            
            while(result.next()){
                idClientCompoire_BDD = result.getInt("C_GidClientcomptoire");
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return idClientCompoire_BDD;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonValiderCarte;
    private javax.swing.JLabel ErreurLabel;
    private javax.swing.JDialog GestionFid;
    private javax.swing.JLabel NomLogiciel;
    private javax.swing.JLabel NomLogiciel1;
    private javax.swing.JLabel NomLogiciel2;
    private javax.swing.JLabel NomLogiciel3;
    private javax.swing.ButtonGroup buttonGroupAcIn;
    private javax.swing.JDialog confirmSupp;
    private javax.swing.JDialog erreurClientComptoir;
    private javax.swing.JDialog erreurSupprClient;
    private javax.swing.JButton jButtonCSNon;
    private javax.swing.JButton jButtonCSOui;
    private javax.swing.JButton jButtonCarteFid;
    private javax.swing.JButton jButtonCreer;
    private javax.swing.JButton jButtonErreurFermer;
    private javax.swing.JButton jButtonErreurFermer1;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSuprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCodeBar;
    private javax.swing.JLabel jLabelDateCreation;
    private javax.swing.JLabel jLabelDernierModif;
    private javax.swing.JLabel jLabelDernierModif1;
    private javax.swing.JLabel jLabelDernierModif2;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNom1;
    private javax.swing.JLabel jLabelNom2;
    private javax.swing.JLabel jLabelNom3;
    private javax.swing.JLabel jLabelPrénom;
    private javax.swing.JLabel jLabelPrénom1;
    private javax.swing.JLabel jLabelPrénom2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonActif;
    private javax.swing.JRadioButton jRadioButtonInactif;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldCodeClient;
    private javax.swing.JTextField jTextFieldDateCreation;
    private javax.swing.JTextField jTextFieldDerniereModif;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldGnoFid;
    private javax.swing.JTextField jTextFieldGpts;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldNumCarteFid;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldSoldePts;
    private javax.swing.JTextField jTextFieldTel;
    private javax.swing.JTextField jTextFieldVille;
    private javax.swing.JButton nouvelleCarteFid;
    // End of variables declaration//GEN-END:variables
}
