/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import com.formdev.flatlaf.FlatLightLaf;
import com.mysql.jdbc.exceptions.jdbc4.CommunicationsException;
import extend.UserListCellRenderer;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author etien
 */
public class MoyensDePaiement extends javax.swing.JFrame {
    private static Connection conn = Bdd.coBdd(); //Instanciation de la variable de connexion à la base de données

    private static int NbColonneMoyenPaiement = 2;
    private static Object[][] MoyensPaiement = new Object[countMoyensPaiement()][NbColonneMoyenPaiement];
    private static String [] nomColMoyensPaiement = { "ID", "Moyens Paiement"};
    private static int dernierIndiceLigne;

    /**
     * Creates new form TVA
     */
    public MoyensDePaiement() {
        initComponents();
        URL iconURL = getClass().getResource(Données.getUrl_Logo());
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        NomLogiciel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        boutonValider = new javax.swing.JButton();
        boutonAjouter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Données.getNomLogiciel() + " | Fichier Moyens de Paiement ");
        setResizable(false);
        setSize(new java.awt.Dimension(654, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel4.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel4.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel4.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NomLogiciel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomLogiciel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        UserListCellRenderer cellRenderer = new UserListCellRenderer();
        jTable1.setDefaultRenderer(Integer.class, cellRenderer);
        jTable1.setDefaultRenderer(String.class, cellRenderer);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            MoyensPaiement,
            nomColMoyensPaiement) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(51, 153, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(130, 244, 15));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTable1);

        boutonValider.setBackground(new java.awt.Color(102, 255, 102));
        boutonValider.setText("Valider");
        boutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderActionPerformed(evt);
            }
        });

        boutonAjouter.setText("Ajouter");
        boutonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(boutonAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boutonValider)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonValider)
                    .addComponent(boutonAjouter))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boutonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderActionPerformed
        if (jTable1.getRowCount() == countMoyensPaiement()){
            System.out.println("MAJ des lignes existantes seulement ");
            for(int i = 0; i< countMoyensPaiement();i++){
                try {
                    String sql = "UPDATE MoyenDePaiment SET MDP_Type= ? WHERE idMoyenDePaiment = ?";
                    PreparedStatement majMDP = conn.prepareStatement(sql);
                    majMDP.setString(1, jTable1.getValueAt(i, 1).toString());
                    majMDP.setString(2, jTable1.getValueAt(i, 0).toString());
                    
                    majMDP.execute();
                    majMDP.close();
                } catch (SQLException ex) {
                    Logger.getLogger(MoyensDePaiement.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            System.out.println("MAJ lignes existantes");
            for(int i = 0; i< countMoyensPaiement();i++){
                try {
                    String sql = "UPDATE MoyenDePaiment SET MDP_Type= ? WHERE idMoyenDePaiment = ?";
                    PreparedStatement majMDP = conn.prepareStatement(sql);
                    majMDP.setString(1, jTable1.getValueAt(i, 1).toString());
                    majMDP.setString(2, jTable1.getValueAt(i, 0).toString());
                    
                    majMDP.execute();
                    majMDP.close();
                } catch (SQLException ex) {
                    Logger.getLogger(MoyensDePaiement.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            System.out.println("Ajout des nouvelles lignes");
            for(int i = countMoyensPaiement(); i< jTable1.getRowCount() ;i++){
                try {
                    String sql = "INSERT INTO MoyenDePaiment SET MDP_Type= ?";
                    PreparedStatement creationMoyensPaiement = conn.prepareStatement(sql);
                    creationMoyensPaiement.setString(1, jTable1.getValueAt(i, 1).toString());
                    
                    creationMoyensPaiement.execute();
                    creationMoyensPaiement.close();
                } catch (SQLException ex) {
                    Logger.getLogger(MoyensDePaiement.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
    }//GEN-LAST:event_boutonValiderActionPerformed

    private void boutonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjouterActionPerformed
        MoyensPaiement = new Object[countMoyensPaiement()+1][NbColonneMoyenPaiement];
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{dernierIndiceLigne+1});
        dernierIndiceLigne++;
    }//GEN-LAST:event_boutonAjouterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if(Données.getDUA_Admin() == 1){
            
            recupMoyensPaiement();
            
            try {
                UIManager.setLookAndFeel( new FlatLightLaf() );
            } catch( Exception ex ) {
                System.err.println( "Failed to initialize LaF" );
            }

            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new MoyensDePaiement().setVisible(true);
                }
            });
        }else{
            ViolationDroit.main(null);
        }
        
    }
    
    private static int countMoyensPaiement(){ 
        int i = 0;
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT COUNT(*) FROM MoyenDePaiment");
            
            while(result.next()){
                i = result.getInt("COUNT(*)");
            }
            System.out.println("CountMoyensPaiement : " + i);
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return i;
    }
    
    public static void recupMoyensPaiement(){
        try {
            Statement stateMoyensPaiement = conn.createStatement();
            ResultSet recupMoyensPaiement = stateMoyensPaiement.executeQuery("SELECT * FROM MoyenDePaiment");
            
            int i = 0;
            while(recupMoyensPaiement.next()){
                System.out.println("recupMotfES : "+ i);
                MoyensPaiement[i][0] = recupMoyensPaiement.getString("idMoyenDePaiment");
                MoyensPaiement[i][1] = recupMoyensPaiement.getString("MDP_Type");
                i++;
            }
            dernierIndiceLigne = i;
            
            recupMoyensPaiement.close();
            stateMoyensPaiement.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomLogiciel4;
    private javax.swing.JButton boutonAjouter;
    private javax.swing.JButton boutonValider;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
