/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import com.formdev.flatlaf.FlatLightLaf;
import com.mysql.jdbc.exceptions.jdbc4.CommunicationsException;
import extend.UserListCellRenderer;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author etien
 */
public class TicketDeCaisse extends javax.swing.JFrame {
    private static Connection conn = Bdd.coBdd(); //Instanciation de la variable de connexion à la base de données

    private static int NbColonneTDC = 9;
    private static Object[][] TDC = new Object[1][NbColonneTDC];
    private static String [] nomColTDC = { "Code Barre", "Désignation article", "Prix TTC", "Quantité", "Réduction %", "TOTAL Ligne", "#idarticle", "#prixHT", "#totalLigneHT"};

    private static boolean[] EditR = new boolean[] {true, false, false, false, false, false, false, false, false };
    private static boolean[] EditR_edit = new boolean[] {false, false, false, true, true, false, false, false, false };
    ArrayList<boolean[]> canEdit = new ArrayList<boolean[]>();
    
    
    
    private static int etatAjout = 0 ;
    private static double totalTTC = 0.0;
    private static double totalHT = 0.0;
    
    
    
    //variable pour le client selectionné
    private static String C_CodeClient = "0";
    private static String C_Nom;
    private static String C_Prenom;
    private static String C_DateCrea;
    private static String C_Email;
    private static String C_Adresse;
    private static String C_CodePostale;
    private static String C_Ville;
    private static String C_Tel;
    private static String CarteFid_idCarteFid;
    private static int CF_Points;
    
    private static int confirmMDP = 0;
    private static float remise = 0;
    
    
    private static String contenuBlocNote;

    /**
     * Creates new form TicketDeCaisse
     */
    public TicketDeCaisse() {
        initComponents();
        URL iconURL = getClass().getResource(Données.getUrl_Logo());
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        erreurArticleInexistant.setIconImage(icon.getImage());
        erreurArticleInexistant.setLocationRelativeTo(this);
        selClient.setIconImage(icon.getImage());
        selClient.setLocationRelativeTo(this);
        validerTDC.setIconImage(icon.getImage());
        validerTDC.setLocationRelativeTo(this);
        controlePrixTDC.setIconImage(icon.getImage());
        controlePrixTDC.setLocationRelativeTo(this);
        blocNoteTDC.setIconImage(icon.getImage());
        blocNoteTDC.setLocationRelativeTo(this);
        setExtendedState(JFrame.MAXIMIZED_BOTH); // ouvrture de la fenetre en full screen
        
        canEdit.add(EditR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        erreurArticleInexistant = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jButtonErreurFermer1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        NomLogiciel2 = new javax.swing.JLabel();
        selClient = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        NomLogiciel3 = new javax.swing.JLabel();
        CodeClientSaisi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        labelErreurCodeClient = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        validerTDC = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        NomLogiciel4 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        labelConfirmNomPrenomClient = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelConfirmNumClient = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelConfirmNbPts = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelConfirmAdresse = new javax.swing.JLabel();
        labelConfirmCPVille = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        labelConfirmMail = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelConfirmTEL = new javax.swing.JLabel();
        labelConfirmDateCréa = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelConfirmTotalHT = new javax.swing.JLabel();
        labelConfirmTotalTTC = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        MDPlabel = new javax.swing.JLabel();
        blocNoteTDC = new javax.swing.JDialog();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        NomLogiciel5 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        textareaBlocNote = new javax.swing.JTextArea();
        validerBlocNote = new javax.swing.JButton();
        controlePrixTDC = new javax.swing.JDialog();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        NomLogiciel6 = new javax.swing.JLabel();
        codeBarreSaisie = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        erreurControlePrixTDC = new javax.swing.JLabel();
        AfficheControlePrixTDC = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        NomLogiciel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelTotalHT = new javax.swing.JLabel();
        LabelTotalTTC = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        labelNomPrenomClient = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelCodeClient = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelNbPts = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        erreurArticleInexistant.setTitle(Données.getNomLogiciel() + " | Erreur de suppression");
        erreurArticleInexistant.setAlwaysOnTop(true);
        erreurArticleInexistant.setIconImage(null);
        erreurArticleInexistant.setMinimumSize(new java.awt.Dimension(400, 234));
        erreurArticleInexistant.setResizable(false);
        erreurArticleInexistant.setSize(new java.awt.Dimension(400, 176));

        jPanel8.setMinimumSize(new java.awt.Dimension(400, 234));

        jButtonErreurFermer1.setText("Fermer");
        jButtonErreurFermer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonErreurFermer1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Erreur : L'article saisi est inexistant ou desactivé ! ");

        jPanel9.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel2.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel2.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel2.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NomLogiciel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel11))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButtonErreurFermer1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonErreurFermer1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout erreurArticleInexistantLayout = new javax.swing.GroupLayout(erreurArticleInexistant.getContentPane());
        erreurArticleInexistant.getContentPane().setLayout(erreurArticleInexistantLayout);
        erreurArticleInexistantLayout.setHorizontalGroup(
            erreurArticleInexistantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        erreurArticleInexistantLayout.setVerticalGroup(
            erreurArticleInexistantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        selClient.setResizable(false);
        selClient.setSize(new java.awt.Dimension(528, 318));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel10.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel3.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel3.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel3.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NomLogiciel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel3)
                .addContainerGap())
        );

        CodeClientSaisi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CodeClientSaisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeClientSaisiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Code Client : ");

        jButton6.setText("Valider");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        labelErreurCodeClient.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelErreurCodeClient.setForeground(new java.awt.Color(255, 0, 0));

        jButton7.setText("Fichier Client");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(labelErreurCodeClient, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(CodeClientSaisi, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodeClientSaisi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErreurCodeClient, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout selClientLayout = new javax.swing.GroupLayout(selClient.getContentPane());
        selClient.getContentPane().setLayout(selClientLayout);
        selClientLayout.setHorizontalGroup(
            selClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        selClientLayout.setVerticalGroup(
            selClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        validerTDC.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        validerTDC.setTitle(Données.getNomLogiciel() + " | Validation : Ticket de caisse ");
        validerTDC.setResizable(false);
        validerTDC.setSize(new java.awt.Dimension(880, 650));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel11.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel4.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel4.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel4.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NomLogiciel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel4)
                .addContainerGap())
        );

        jButton10.setBackground(new java.awt.Color(255, 204, 102));
        jButton10.setText("Carte Banquaire");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setText("Client : ");

        labelConfirmNomPrenomClient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelConfirmNomPrenomClient.setText("Client comptoir");

        jLabel12.setForeground(new java.awt.Color(0, 153, 255));
        jLabel12.setText("Numéro : ");

        labelConfirmNumClient.setText("1");

        jLabel13.setForeground(new java.awt.Color(0, 153, 255));
        jLabel13.setText("Points :");

        jLabel16.setForeground(new java.awt.Color(0, 153, 255));
        jLabel16.setText("Adresse :");

        jLabel17.setForeground(new java.awt.Color(0, 153, 255));
        jLabel17.setText("Mail :");

        jLabel18.setForeground(new java.awt.Color(0, 153, 255));
        jLabel18.setText("TEL :");

        jLabel19.setForeground(new java.awt.Color(0, 153, 255));
        jLabel19.setText("Date Création :");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(27, 27, 27)
                        .addComponent(labelConfirmNomPrenomClient, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(labelConfirmNbPts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel18)))
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(labelConfirmTEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelConfirmNumClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelConfirmAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel19)
                                .addGap(6, 6, 6)
                                .addComponent(labelConfirmDateCréa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelConfirmCPVille, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelConfirmMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelConfirmNomPrenomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(labelConfirmNumClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelConfirmAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelConfirmCPVille, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelConfirmMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelConfirmTEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(labelConfirmDateCréa, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConfirmNbPts, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jButton11.setBackground(new java.awt.Color(255, 204, 102));
        jButton11.setText("Espèces");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(0, 204, 0));
        jButton13.setText("Valider TDC");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("TOTAL HT : ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 255));
        jLabel14.setText("TOTAL TTC : ");

        labelConfirmTotalHT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelConfirmTotalHT.setLabelFor(jLabel2);
        labelConfirmTotalHT.setText("0.00 €");

        labelConfirmTotalTTC.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelConfirmTotalTTC.setLabelFor(jLabel2);
        labelConfirmTotalTTC.setText("0.00 €");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelConfirmTotalHT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelConfirmTotalTTC, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConfirmTotalHT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConfirmTotalTTC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jButton14.setBackground(new java.awt.Color(255, 204, 102));
        jButton14.setText("Chèque");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        MDPlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MDPlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(MDPlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MDPlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout validerTDCLayout = new javax.swing.GroupLayout(validerTDC.getContentPane());
        validerTDC.getContentPane().setLayout(validerTDCLayout);
        validerTDCLayout.setHorizontalGroup(
            validerTDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        validerTDCLayout.setVerticalGroup(
            validerTDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        blocNoteTDC.setTitle(Données.getNomLogiciel() + " | Bloc note ");
        blocNoteTDC.setResizable(false);
        blocNoteTDC.setSize(new java.awt.Dimension(540, 565));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel15.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel5.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel5.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel5.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NomLogiciel5, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel5)
                .addContainerGap())
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BlocNoteIcon.png"))); // NOI18N
        jLabel20.setText("                    BLOC_NOTE");

        textareaBlocNote.setColumns(20);
        textareaBlocNote.setRows(5);
        textareaBlocNote.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(textareaBlocNote);

        validerBlocNote.setBackground(new java.awt.Color(0, 255, 0));
        validerBlocNote.setText("VALIDER");
        validerBlocNote.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        validerBlocNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerBlocNoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(validerBlocNote)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(validerBlocNote)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout blocNoteTDCLayout = new javax.swing.GroupLayout(blocNoteTDC.getContentPane());
        blocNoteTDC.getContentPane().setLayout(blocNoteTDCLayout);
        blocNoteTDCLayout.setHorizontalGroup(
            blocNoteTDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        blocNoteTDCLayout.setVerticalGroup(
            blocNoteTDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        controlePrixTDC.setTitle(Données.getNomLogiciel() + " | Contrôle Prix ");
        controlePrixTDC.setResizable(false);
        controlePrixTDC.setSize(new java.awt.Dimension(800, 337));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel18.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel6.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel6.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel6.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NomLogiciel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel6)
                .addContainerGap())
        );

        codeBarreSaisie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codeBarreSaisie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeBarreSaisieActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Code Barre : ");

        jButton8.setBackground(new java.awt.Color(153, 255, 153));
        jButton8.setText("Valider");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        erreurControlePrixTDC.setBackground(new java.awt.Color(255, 255, 255));
        erreurControlePrixTDC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        erreurControlePrixTDC.setForeground(new java.awt.Color(204, 0, 0));
        erreurControlePrixTDC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        AfficheControlePrixTDC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AfficheControlePrixTDC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(codeBarreSaisie, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
            .addComponent(AfficheControlePrixTDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(erreurControlePrixTDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(erreurControlePrixTDC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeBarreSaisie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(AfficheControlePrixTDC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout controlePrixTDCLayout = new javax.swing.GroupLayout(controlePrixTDC.getContentPane());
        controlePrixTDC.getContentPane().setLayout(controlePrixTDCLayout);
        controlePrixTDCLayout.setHorizontalGroup(
            controlePrixTDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        controlePrixTDCLayout.setVerticalGroup(
            controlePrixTDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Données.getNomLogiciel() + " | Ticket de caisse ");
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(Données.getCouleurPrincipale1(), Données.getCouleurPrincipale2(), Données.getCouleurPrincipale3()));

        NomLogiciel.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        NomLogiciel.setForeground(new java.awt.Color(255, 255, 255));
        NomLogiciel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomLogiciel.setText(Données.getNomLogiciel());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(NomLogiciel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomLogiciel)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("TOTAL HT : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("TOTAL TTC : ");

        LabelTotalHT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelTotalHT.setLabelFor(jLabel2);
        LabelTotalHT.setText("0.00 €");

        LabelTotalTTC.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LabelTotalTTC.setLabelFor(jLabel2);
        LabelTotalTTC.setText("0.00 €");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTotalHT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelTotalTTC, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTotalHT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTotalTTC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("Création Ticket de Caisse");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Client : ");

        labelNomPrenomClient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNomPrenomClient.setText("Client comptoir");

        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Numéro : ");

        labelCodeClient.setText(C_CodeClient);

        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("Points :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(labelNomPrenomClient, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(labelNbPts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(labelCodeClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelNomPrenomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelCodeClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelNbPts, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Duplicatat");

        jButton2.setText("Bloc note");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Controle prix");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Client");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 204, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("TOTAL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        UserListCellRenderer cellRenderer = new UserListCellRenderer();
        jTable1.setDefaultRenderer(String.class, cellRenderer);
        jTable1.setDefaultRenderer(Float.class, cellRenderer);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            TDC,
            nomColTDC) {
            Class[] types = new Class [] {
                java.lang.String.class,java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                boolean[] cc = canEdit.get(rowIndex);
                return cc[columnIndex];
            }

        });
        jTable1.getModel().addTableModelListener(
            new TableModelListener()
            {
                public void tableChanged(TableModelEvent evt)
                {
                    AjoutDonnée(evt);
                }
            });
            jTable1.setGridColor(new java.awt.Color(51, 153, 255));
            jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
            jTable1.setRowHeight(30);
            jTable1.setSelectionBackground(new java.awt.Color(130, 244, 15));
            jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
            jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            jScrollPane1.setViewportView(jTable1);
            if (jTable1.getColumnModel().getColumnCount() > 0) {
                //cacher les colones avec ses 3 lignes suiventes
                jTable1.getColumnModel().getColumn(6).setMaxWidth(0);
                jTable1.getColumnModel().getColumn(6).setMinWidth(0);
                jTable1.getColumnModel().getColumn(6).setPreferredWidth(0);
                jTable1.getColumnModel().getColumn(7).setMaxWidth(0);
                jTable1.getColumnModel().getColumn(7).setMinWidth(0);
                jTable1.getColumnModel().getColumn(7).setPreferredWidth(0);
                jTable1.getColumnModel().getColumn(8).setMaxWidth(0);
                jTable1.getColumnModel().getColumn(8).setMinWidth(0);
                jTable1.getColumnModel().getColumn(8).setPreferredWidth(0);

            }

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(119, 119, 119)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(52, 52, 52)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1564, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(276, 276, 276)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(55, 55, 55)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(64, 64, 64))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void jButtonErreurFermer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonErreurFermer1ActionPerformed
        erreurArticleInexistant.setVisible(false);
    }//GEN-LAST:event_jButtonErreurFermer1ActionPerformed

    private void CodeClientSaisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeClientSaisiActionPerformed
        selectClient();
    }//GEN-LAST:event_CodeClientSaisiActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        FichierClient.main(null);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        selClient.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (totalTTC != 0 && totalHT != 0){
            
            labelConfirmNomPrenomClient.setText(labelNomPrenomClient.getText());
            labelConfirmNumClient.setText(C_CodeClient);
            labelConfirmAdresse.setText(C_Adresse);
            labelConfirmCPVille.setText(C_CodePostale + " " + C_Ville);
            labelConfirmMail.setText(C_Email);
            labelConfirmTEL.setText(C_Tel);
            labelConfirmDateCréa.setText(C_DateCrea);
            labelConfirmNbPts.setText(String.valueOf(CF_Points));

            DecimalFormat df = new DecimalFormat("#0.00");
            DecimalFormatSymbols Symbole = new DecimalFormatSymbols();
            Symbole.setDecimalSeparator('.');
            df.setDecimalFormatSymbols(Symbole);
            labelConfirmTotalTTC.setText(df.format(totalTTC) + " €");
            labelConfirmTotalHT.setText(df.format(totalHT) + " €");

            validerTDC.setVisible(true);

            if ( CF_Points > 0){
                float remis = 0;
                try {
                    String sql = "SELECT PF_ReducEuro FROM PalierFid WHERE PF_PalierPts < ? ORDER BY PF_ReducEuro DESC";
                    PreparedStatement findART = conn.prepareStatement(sql);
                    findART.setInt(1,CF_Points);
                    ResultSet result = findART.executeQuery();

                    int F = 0;
                    while(result.next() && F == 0){
                        remise = result.getFloat("PF_ReducEuro");
                        F = 1;
                    }

                    findART.execute();
                    findART.close();

                } 
                catch (CommunicationsException e) {
                    Bdd.lostCO(e);        
                }
                catch (SQLException ex) {
                    Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(remise + " €");
            }
        }//else total 0€
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        recupBlocNote();
        blocNoteTDC.setVisible(true);
        textareaBlocNote.setText(contenuBlocNote);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void validerBlocNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerBlocNoteActionPerformed
        try {
            String sql = "UPDATE BlocNote set contenuBlocNote=? where idBlocNote=1"; // update le contenu du bloc note dans la base de données
            PreparedStatement validerBlocNote = conn.prepareStatement(sql);
            validerBlocNote.setString(1,textareaBlocNote.getText() ); // on remplace le premier '?' par le contenu de la zone de texte
            validerBlocNote.execute(); // On execute la requete SQL
            validerBlocNote.close(); // on ferme la requete
            recupBlocNote();
            InterfaceUser.recupBlocNote();
            blocNoteTDC.dispose();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e); // Si il y a un probleme de connexion on lance la fenetre de perte de connexion
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex); // rapport d'erreur SQL
        }
    }//GEN-LAST:event_validerBlocNoteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        controlePrixTDC.setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void codeBarreSaisieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeBarreSaisieActionPerformed
        AfficheControlePrixTDC.setVisible(true);
        ControlePrix();
// TODO add your handling code here:
    }//GEN-LAST:event_codeBarreSaisieActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        AfficheControlePrixTDC.setVisible(true);
        ControlePrix();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        selectClient();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        totalTTC = 0.0;
        totalHT = 0.0;
    }//GEN-LAST:event_formWindowClosed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        confirmMDP = 1;
        MDPlabel.setText("Moyen de paiement sélectionné : carte bancaire ");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        confirmMDP= 2;
        MDPlabel.setText("Moyen de paiement sélectionné : espèces");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        confirmMDP = 3;
        MDPlabel.setText("Moyen de paiement sélectionné : chèque");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try {
            String sqlinsertTDC = "INSERT INTO TicketDeCaisse( TDC_RemiseTicket, TDC_Date, TDC_Heure, Client_idClient, MoyenDePaiment_idMoyenDePaiment, UserApp_iduser_app) VALUES (?,?,?,?,?,?)";
            PreparedStatement insertTDC = conn.prepareStatement(sqlinsertTDC);
            
            LocalDate localDate = LocalDate.now();
            LocalTime localTime = LocalTime.now();
            
            insertTDC.setFloat(1,remise);
            insertTDC.setString(2,localDate.toString());
            insertTDC.setString(3,localTime.toString());
            insertTDC.setString(4,labelConfirmNumClient.getText());
            insertTDC.setInt(5,confirmMDP);
            insertTDC.setInt(6,Données.getDUA_Id());

            insertTDC.execute();
            
            
            String sqlmaxid = "SELECT MAX(idTicketDeCaisse) FROM TicketDeCaisse;";
            Statement maxIdStatement = conn.createStatement();
            ResultSet result = maxIdStatement.executeQuery(sqlmaxid);
            int maxid = 0;
            while(result.next()){
                maxid = result.getInt("MAX(idTicketDeCaisse)");
            }
            
            insertTDC.close();
            
            String sqlLTDC = "INSERT INTO LigneTDC (LTDC_Quantite, LTDC_RemiseLigne, Article_idArticle, TicketDeCaisse_idTicketDeCaisse) VALUES (?, ?, ?, ?);";
            PreparedStatement insertLTDC = conn.prepareStatement(sqlLTDC);
            
            int longueurTable = jTable1.getRowCount()-1;
            System.out.println(longueurTable);
            for(int i = 0; i<longueurTable;i++){
                insertLTDC.setString(1,jTable1.getValueAt(i, 3).toString());
                insertLTDC.setString(2,jTable1.getValueAt(i, 4).toString());
                insertLTDC.setString(3,jTable1.getValueAt(i, 6).toString());
                insertLTDC.setInt(4,maxid);
                
                insertLTDC.execute();
            }
            
            insertLTDC.close();
            
        
        }catch (CommunicationsException e) {
            Bdd.lostCO(e);       
            
        }catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
    }//GEN-LAST:event_jButton13ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if(Données.getDUA_Encaissement() == 1){ //Verifie si l'utilisateur qui s'est connecté a les droits sur l'encaissement
            IdClientComptoir();
            try {
                UIManager.setLookAndFeel( new FlatLightLaf() );
            } catch( Exception ex ) {
                System.err.println( "Failed to initialize LaF" );
            }

            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new TicketDeCaisse().setVisible(true);
                }
            });
        }else{
            ViolationDroit.main(null);
        }
    }
    
    public void ControlePrix(){
        
        int exist=0;
        
        try {
            String sql = "SELECT COUNT(*) FROM Article WHERE A_EAN = ? AND A_Statut = 1";
            PreparedStatement findART = conn.prepareStatement(sql);
            findART.setString(1,codeBarreSaisie.getText());
            ResultSet result = findART.executeQuery();

            while(result.next()){

            exist = result.getInt("COUNT(*)");
        }

        findART.execute();
        findART.close();
        
        } 
        catch (CommunicationsException e) {
            Bdd.lostCO(e);        
        }
        catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(exist == 1){
             try {
                 String sql = "SELECT A_Designation, A_PrixDeVente FROM Article WHERE A_EAN = ? AND A_Statut = 1";
                 PreparedStatement findART = conn.prepareStatement(sql);
                 findART.setString(1,codeBarreSaisie.getText());
                 ResultSet result = findART.executeQuery();

                 while(result.next()){
                     AfficheControlePrixTDC.setText(result.getString("A_Designation")+" :  "+result.getString("A_PrixDeVente")+" € TTC");
                 }
                 findART.execute();
                 findART.close();
                 erreurControlePrixTDC.setText("");

                 majTotalTTCLabel();

             } 
             catch (CommunicationsException e) {
                 Bdd.lostCO(e);        
             } 
             catch (SQLException ex) {
                 Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
             }
         }
        
        else{
            erreurControlePrixTDC.setText("L'ARTICLE EST INTROUVABLE !");
            AfficheControlePrixTDC.setVisible(false);
        }
        
    }
    
    public void AjoutDonnée(TableModelEvent evt){
        int col = evt.getColumn();
        int row = evt.getFirstRow();
        
        
        if (col == 0){
            etatAjout = 1;
            String codeBarreSaisie = jTable1.getModel().getValueAt(row, col).toString();
            int exist = 1;
            //recherche infos article
            
            try {
                String sql = "SELECT COUNT(*) FROM Article WHERE A_EAN = ? AND A_Statut = 1";
                PreparedStatement findART = conn.prepareStatement(sql);
                findART.setString(1,codeBarreSaisie);
                ResultSet result = findART.executeQuery();
            
                while(result.next()){
                    
                    exist = result.getInt("COUNT(*)");
                }
                
                findART.execute();
                findART.close();
            } catch (CommunicationsException e) {
                Bdd.lostCO(e);        
            }catch (SQLException ex) {
                Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(exist == 1){
                float tauxTVA = 0;
                try {
                    String sql = "SELECT * FROM Article JOIN TVA ON Article.TVA_idTVA = TVA.idTVA WHERE A_EAN = ? AND A_Statut = 1";
                    PreparedStatement findART = conn.prepareStatement(sql);
                    findART.setString(1,codeBarreSaisie);
                    ResultSet result = findART.executeQuery();

                    while(result.next()){
                        jTable1.getModel().setValueAt(result.getString("A_Designation"), row, 1);
                        jTable1.getModel().setValueAt(result.getFloat("A_PrixDeVente"), row, 2);
                        jTable1.getModel().setValueAt(1, row, 3);
                        jTable1.getModel().setValueAt(0, row, 4);
                        jTable1.getModel().setValueAt(result.getFloat("A_PrixDeVente"), row, 5);
                        jTable1.getModel().setValueAt(result.getFloat("idArticle"), row, 6);
                        tauxTVA = result.getFloat("TVA_Taux");
                        totalTTC = totalTTC + result.getFloat("A_PrixDeVente");
                    }
                    findART.execute();
                    findART.close();
                    
                    float ht = (float) jTable1.getModel().getValueAt(row, 2) - ( tauxTVA * (float) jTable1.getModel().getValueAt(row, 2));
                    jTable1.getModel().setValueAt(ht, row, 7);
                    jTable1.getModel().setValueAt(ht, row, 8);
                    totalHT = totalHT + ht;
                    System.out.println(ht);
                    majTotalTTCLabel();
                    majTotalHTLabel();
                    
                } catch (CommunicationsException e) {
                    Bdd.lostCO(e);        
                } catch (SQLException ex) {
                    Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                //ajout ligne suivante
                canEdit.set(row, EditR_edit);
                canEdit.add(EditR);
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(new Object[]{"","","","","","",""});
            } else {
                System.err.println("errrrrrr de code barre");
                erreurArticleInexistant.setVisible(true);
                
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.removeRow(row);
                model.addRow(new Object[]{""});
                
            }
            
            etatAjout = 0;
            
        } else if (col == 3 && etatAjout == 0 || col == 4 && etatAjout == 0){
            float lastTotalLigne = (float) jTable1.getModel().getValueAt(row, 5);
            totalTTC -= lastTotalLigne;
            float QTTsaisi = Float.valueOf(jTable1.getModel().getValueAt(row, 3).toString());
            float Rsaisi = Float.valueOf(jTable1.getModel().getValueAt(row, 4).toString());
            float prixProduit = (float) jTable1.getModel().getValueAt(row, 2);
            float MontantR = Rsaisi/100 * prixProduit * QTTsaisi;
            float newTotalLigne = prixProduit * QTTsaisi - MontantR;
            jTable1.getModel().setValueAt(newTotalLigne, row, 5);
            totalTTC += newTotalLigne;
            majTotalTTCLabel();
            
            float lastTotalLigneHT = (float) jTable1.getModel().getValueAt(row, 8);
            totalHT -= lastTotalLigneHT;
            float prixProduitHT = (float) jTable1.getModel().getValueAt(row, 7);
            float MontantRHT = Rsaisi/100 * prixProduitHT * QTTsaisi;
            float newTotalLigneHT = prixProduitHT * QTTsaisi - MontantRHT;
            jTable1.getModel().setValueAt(newTotalLigneHT, row, 8);
            totalHT += newTotalLigneHT;
            majTotalHTLabel();
            
            
        }
    
    }
    
    private void selectClient(){
        int exist = 0;
        try {
            String sql = "SELECT COUNT(*) FROM Client WHERE idClient = ?";
            PreparedStatement findClient = conn.prepareStatement(sql);
            findClient.setString(1,CodeClientSaisi.getText());
            ResultSet result = findClient.executeQuery();

            while(result.next()){
                exist = result.getInt("COUNT(*)");
            }

            findClient.execute();
            findClient.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);        
        }catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (exist == 1){
            try {
                String sql = "SELECT * FROM Client WHERE idClient = ? AND C_Statut = 1";
                PreparedStatement findClientInfos = conn.prepareStatement(sql);
                findClientInfos.setString(1,CodeClientSaisi.getText());
                ResultSet result = findClientInfos.executeQuery();
                
                C_CodeClient = CodeClientSaisi.getText();
                while(result.next()){
                    C_Nom = result.getString("C_Nom");
                    C_Prenom = result.getString("C_Prenom");
                    C_DateCrea = result.getString("C_DateCrea");
                    C_Email = result.getString("C_Email");
                    C_Adresse = result.getString("C_Adresse");
                    C_CodePostale = result.getString("C_CodePostale");
                    C_Ville = result.getString("C_Ville");
                    C_Tel = result.getString("C_Tel");
                    CarteFid_idCarteFid = result.getString("CarteFid_idCarteFid");
                }
                
                findClientInfos.execute();
                findClientInfos.close();
                
            } catch (CommunicationsException e) {
                Bdd.lostCO(e);        
            }catch (SQLException ex) {
                Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (CarteFid_idCarteFid != null){
                try {
                    String sql = "SELECT CF_Points FROM CarteFid WHERE idCarteFid = ?";
                    PreparedStatement findClient = conn.prepareStatement(sql);
                    findClient.setString(1,CarteFid_idCarteFid);
                    ResultSet result = findClient.executeQuery();

                    while(result.next()){
                        CF_Points = result.getInt("CF_Points");
                    }
                    labelNbPts.setText(String.valueOf(CF_Points));
                    findClient.execute();
                    findClient.close();
                 } catch (CommunicationsException e) {
                    Bdd.lostCO(e);        
                 }catch (SQLException ex) {
                    Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
                 } 
               
            } else {
                CF_Points = 0;
                labelNbPts.setText(String.valueOf(CF_Points));
            }
            
            
            labelNomPrenomClient.setText(C_Nom +" "+ C_Prenom );
            labelCodeClient.setText(C_CodeClient);
            
            selClient.dispose();
            
        } else {
            labelErreurCodeClient.setText("Client Introuvable !");
        }
    }
    
    
    private void majTotalTTCLabel(){
        DecimalFormat df = new DecimalFormat("#0.00");
        DecimalFormatSymbols Symbole = new DecimalFormatSymbols();
        Symbole.setDecimalSeparator('.');
        df.setDecimalFormatSymbols(Symbole);

        LabelTotalTTC.setText(df.format(totalTTC) + " €");
    }
    
    private void majTotalHTLabel(){
        DecimalFormat df = new DecimalFormat("#0.00");
        DecimalFormatSymbols Symbole = new DecimalFormatSymbols();
        Symbole.setDecimalSeparator('.');
        df.setDecimalFormatSymbols(Symbole);

        LabelTotalHT.setText(df.format(totalHT) + " €");
    }
    
        public static void recupBlocNote(){
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT contenuBlocNote FROM BlocNote WHERE idBlocNote = 1"); // on récupere le contenu de bloc note dans la base de données
            
            while(result.next()){
                contenuBlocNote = result.getString("contenuBlocNote");
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
       
    } 
          
    private static int IdClientComptoir(){ 
        int idClientCompoire_BDD = 1;
        try {
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery("SELECT C_GidClientcomptoire FROM Conf_G");
            
            while(result.next()){
                C_CodeClient = result.getString("C_GidClientcomptoire");
            }
            result.close();
            state.close();
        } catch (CommunicationsException e) {
            Bdd.lostCO(e);
        } catch (SQLException ex) {
            Logger.getLogger(ConnexionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return idClientCompoire_BDD;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AfficheControlePrixTDC;
    private javax.swing.JTextField CodeClientSaisi;
    private javax.swing.JLabel LabelTotalHT;
    private javax.swing.JLabel LabelTotalTTC;
    private javax.swing.JLabel MDPlabel;
    private javax.swing.JLabel NomLogiciel;
    private javax.swing.JLabel NomLogiciel2;
    private javax.swing.JLabel NomLogiciel3;
    private javax.swing.JLabel NomLogiciel4;
    private javax.swing.JLabel NomLogiciel5;
    private javax.swing.JLabel NomLogiciel6;
    private javax.swing.JDialog blocNoteTDC;
    private javax.swing.JTextField codeBarreSaisie;
    private javax.swing.JDialog controlePrixTDC;
    private javax.swing.JDialog erreurArticleInexistant;
    private javax.swing.JLabel erreurControlePrixTDC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonErreurFermer1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCodeClient;
    private javax.swing.JLabel labelConfirmAdresse;
    private javax.swing.JLabel labelConfirmCPVille;
    private javax.swing.JLabel labelConfirmDateCréa;
    private javax.swing.JLabel labelConfirmMail;
    private javax.swing.JLabel labelConfirmNbPts;
    private javax.swing.JLabel labelConfirmNomPrenomClient;
    private javax.swing.JLabel labelConfirmNumClient;
    private javax.swing.JLabel labelConfirmTEL;
    private javax.swing.JLabel labelConfirmTotalHT;
    private javax.swing.JLabel labelConfirmTotalTTC;
    private javax.swing.JLabel labelErreurCodeClient;
    private javax.swing.JLabel labelNbPts;
    private javax.swing.JLabel labelNomPrenomClient;
    private javax.swing.JDialog selClient;
    private javax.swing.JTextArea textareaBlocNote;
    private javax.swing.JButton validerBlocNote;
    private javax.swing.JDialog validerTDC;
    // End of variables declaration//GEN-END:variables
}
